@{
  # Language metadata
  "Language.DisplayName"                     = "English"
  "Language.VersionCheckError"               = "[ERROR] PowerShell 7.x or later is required."
  "Language.VersionCheckCurrent"             = "Current"

  # Common
  "Common.Yes"                               = "Yes"
  "Common.No"                                = "No"
  "Common.Success"                           = "Success"
  "Common.Failed"                            = "Failed"
  "Common.Skip"                              = "Skip"
  "Common.Info"                              = "Info"
  "Common.Warn"                              = "Warning"
  "Common.MenuCancel"                        = "Cancel"
  "Common.MenuAll"                           = "All"
  "Common.MenuQuit"                          = "Quit"
  "Common.Cancelled"                         = "Operation cancelled."
  "Common.Welcome"                           = "SSL Certificate Management Tool"
  "Common.PressAnyKey"                       = "Press any key to continue..."
  "Toolkit.ExitConfirmation"                 = "Exiting. Press any key to close..."
  "Common.Prompt.Domain"                     = "Domain"
  "Common.Prompt.Email"                      = "Email"

  "Toolkit.Banner.Title"                     = "SSL Certificate Management Tool"
  "Toolkit.Banner.Version"                   = "Ver {0}  https://github.com/sunshaoxuan"
  "Toolkit.Exit.VersionLine"                 = "Version: {0}"
  "Toolkit.Exit.UpdatedLine"                 = "Last Updated: {0}"
  "Toolkit.Exit.Copyright"                   = "Copyright (c) sunshaoxuan"
  "Toolkit.Exit.Thanks"                      = "Thank you for using SSL Toolkit!"

  # Toolkit menu
  "Toolkit.Menu.Title"                       = "Select Tool (Up/Down to select, Enter to confirm, ESC to exit)"
  "Toolkit.Menu.Exit"                        = "[ Exit ]"
  "Toolkit.Menu.Back"                        = "[ Back ]"
  "Toolkit.Menu.Language"                    = "Language"
  "Toolkit.Menu.SelectLanguage"              = "Select Language"
  "Toolkit.Menu.SubMenuSelect"               = "{0} - Select type"
  "Toolkit.Menu.Starting"                    = "Starting: {0}"
  "Toolkit.Menu.PressAnyKey"                 = "Press any key to return to menu..."
  "Toolkit.Menu.AutoRename"                  = "Startup auto task: organization folder rename check..."
  "Toolkit.Menu.AutoRenameFailed"            = "Auto rename check failed and was skipped: {0}"
  "Toolkit.Menu.ScriptNotFound"              = "Script not found: {0}"

  # Tool descriptions
  "Toolkit.Tool.CertInfo"                    = "View Certificate Info"
  "Toolkit.Tool.CsrFromOld"                  = "Renew CSR from Old Certificate"
  "Toolkit.Tool.NewCsr"                      = "Create New CSR"
  "Toolkit.Tool.MergeChain"                  = "Merge Certificate Chain"
  "Toolkit.Tool.ConvertKey"                  = "Convert Key to Plaintext"
  "Toolkit.Tool.ExportModulus"               = "Export Certificate Modulus"
  "Toolkit.Tool.RepairPem"                   = "Repair PEM File"
  "Toolkit.Tool.ServerList"                  = "Export Certificate Renewal TSV"
  "Toolkit.Tool.SyncMerged"                  = "Sync to output/merged (key,csr,tsv)"
  "Toolkit.Tool.SelfSigned"                  = "Self-Signed Certificate"
  "Toolkit.SubTool.SelfSigned10Y"            = "Generate 10-Year Self-Signed Cert"
  "Toolkit.SubTool.LetsEncrypt"              = "Request Let's Encrypt Certificate"
  "Common.FileNotFound"                      = "{0} not found: {1}"
  "Common.OpenSslCmdFailed"                  = "OpenSSL command failed: {0}`n{1}"
  "Common.Exists"                            = "exists"
  "Common.NotExists"                         = "missing"
  "Common.I18nModuleNotFound"                = "i18n module not found: {0}"
  "Common.DirNotFound"                       = "{0} not found: {1}"

  # Common labels
  "Label.Old"                                = "old"
  "Label.New"                                = "new"
  "Label.Merged"                             = "merged"
  "Label.SelfSigned"                         = "self-signed"
  "Label.Cert"                               = "Certificate"
  "Label.Csr"                                = "CSR"
  "Label.Key"                                = "Private key"
  "Label.File"                               = "File"
  "Label.FileType"                           = "Type"
  "Label.Format"                             = "Format"
  "Label.Blocks"                             = "Cert blocks"
  "Label.HasChain"                           = "Chain included"
  "Label.FinalUse"                           = "Final use"
  "Label.ExtChainCand"                       = "Ext chain candidates"
  "Label.Encrypted"                          = "Encrypted"
  "Label.PassFile"                           = "Pass file"
  "Label.AutoMode"                           = "Unattended mode"
  "Label.DecryptCheck"                       = "Decrypt check"
  "Label.OpenSslDetails"                     = "OpenSSL Details"
  "Label.ChainBlockServer"                   = "Server Certificate"
  "Label.ChainBlockIntermediate"             = "Intermediate CA"
  "Label.ChainBlockRoot"                     = "Root / Cross-Root CA"
  "Label.Subject"                            = "Subject"
  "Label.Issuer"                             = "Issuer"
  "Label.NotBefore"                          = "NotBefore"
  "Label.NotAfter"                           = "NotAfter"
  "Label.TimeZone"                           = "Time Zone"
  "Label.GmtOriginal"                        = "GMT Original"

  # Get-CertificateInfo.ps1
  "CheckBasic.Header"                        = "========== {0} =========="
  "CheckBasic.Dir"                           = "[DIR] {0}"
  "CheckBasic.PassFilePresent"               = "pass:{0}"
  "CheckBasic.PassFileMissing"               = "pass:{0} missing"
  "CheckBasic.PassEnvPresent"                = "PASS_FILE:present"
  "CheckBasic.PassEnvMissingFile"            = "PASS_FILE:not found"
  "CheckBasic.None"                          = "(none)"
  "CheckBasic.NotFound"                      = "not found"
  "CheckBasic.Cert.NotMerged"                = "not merged"
  "CheckBasic.Cert.NeedMerge"                = "merge needed"
  "CheckBasic.Cert.Candidate"                = "candidate:{0}"
  "CheckBasic.Cert.Issuer"                   = "issuer:{0}"
  "CheckBasic.Cert.HasChain"                 = "chain included"
  "CheckBasic.Cert.UsableGuess"              = "usable (guess)"
  "CheckBasic.Cert.Unk"                      = "unknown"
  "CheckBasic.Cert.FormatUnknown"            = "unknown"
  "CheckBasic.Cert.Expiry"                   = "expires:{0}"
  "CheckBasic.Cert.ChainFile"                = "Chain file"
  "CheckBasic.Cert.ChainBlocks"              = "Chain blocks"
  "CheckBasic.Cert.ChainFormat"              = "Chain format"
  "CheckBasic.Cert.ChainFileBlocks"          = "chain:{0}"
  "CheckBasic.Cert.ChainFileFound"           = "chain:found"
  "CheckBasic.Cert.SAN"                      = "SAN"
  "CheckBasic.ChainFileIgnored"              = "[INFO] -ChainFile is only valid with -Path; ignored."
  "CheckBasic.Pretty.CertTitle"              = "Certificates"
  "CheckBasic.Pretty.CsrTitle"               = "CSRs"
  "CheckBasic.Pretty.KeyTitle"               = "Keys"
  "CheckBasic.Pretty.Path"                   = "Path"
  "CheckBasic.Pretty.File"                   = "File"
  "CheckBasic.Pretty.Expiry"                 = "Expiry"
  "CheckBasic.Pretty.Chain"                  = "Chain"
  "CheckBasic.Pretty.ChainFile"              = "Chain File"
  "CheckBasic.Pretty.Blocks"                 = "Blocks"
  "CheckBasic.Pretty.ChainBlocks"            = "Chain Blocks"
  "CheckBasic.Pretty.Issuer"                 = "Issuer"
  "CheckBasic.Pretty.Format"                 = "Format"
  "CheckBasic.Pretty.Subject"                = "Subject"
  "CheckBasic.Pretty.SAN"                    = "SAN"
  "CheckBasic.Pretty.Encrypted"              = "Encrypted"
  "CheckBasic.Pretty.AutoMode"               = "Auto Mode"
  "CheckBasic.Pretty.Decrypt"                = "Decrypt"
  "CheckBasic.Key.Encrypted"                 = "encrypted"
  "CheckBasic.Key.Plain"                     = "plain"
  "CheckBasic.Key.DecOk"                     = "decrypt:ok"
  "CheckBasic.Key.DecFail"                   = "decrypt:fail"
  "CheckBasic.Key.DecSkip"                   = "decrypt:{0}"
  "CheckBasic.Key.AutoOkNoPass"              = "unattended OK (no pass needed)"
  "CheckBasic.Key.AutoOkNeedPass"            = "unattended OK (decrypt needed / no prompt)"
  "CheckBasic.Key.AutoNgNeedPass"            = "unattended NO (no pass and no prompt)"
  "CheckBasic.Key.SkipNoPass"                = "skip(no pass)"
  "CheckBasic.Key.SkipNoPassLong"            = "skip (no pass)"

  # Detail mode labels (Get-CertificateInfo.ps1)
  "CheckBasic.Detail.File"                   = "[FILE] {0}"
  "CheckBasic.Detail.Key"                    = "[KEY]"
  "CheckBasic.Detail.Key.Encrypted"          = "[KEY] Encrypted: {0}"
  "CheckBasic.Detail.Key.PassFile"           = "[KEY] Pass file({0}): {1}"
  "CheckBasic.Detail.Key.EnvPassSet"         = "[KEY] Env PASS_FILE: set ({0} / {1})"
  "CheckBasic.Detail.Key.EnvPassUnset"       = "[KEY] Env PASS_FILE: unset"
  "CheckBasic.Detail.Key.Auto"               = "[KEY] Unattended: {0}"
  "CheckBasic.Detail.Key.DecCheck"           = "[KEY] Decrypt check: {0}"
  "CheckBasic.Detail.Subject"                = "Subject:"
  "CheckBasic.Detail.SAN"                    = "SAN:"
  "CheckBasic.Detail.Key.CannotReadNeedPass" = "[WARN] Cannot read encrypted key (prepare {0} or -PassFile / env PASS_FILE)"
  "CheckBasic.Detail.Key.CannotRead"         = "[WARN] Cannot read key"
  "CheckBasic.Detail.UnsupportedExt"         = "Unsupported extension: {0}"
  "CheckBasic.Detail.Cert.HasPrivateKey"     = "Private Key Included"
  "CheckBasic.Detail.Cert.NoChainHint"       = "[CERT] Note: Intermediate certificate is not included. Use Merge-CertificateChain.ps1 if needed."

  # Merge-CertificateChain.ps1
  "MergeCert.TitleSingle"                    = "Certificate Chain Merger"
  "MergeCert.TitleBatch"                     = "Certificate Chain Merger (Batch)"
  "MergeCert.Step1"                          = "Checking Input Files"
  "MergeCert.Step2"                          = "Normalizing & Merging"
  "MergeCert.ClientCert"                     = "Client Cert"
  "MergeCert.IntermediateCert"               = "Intermediate Cert"
  "MergeCert.AlreadyHasChain"                = "Certificate might already have a chain (Blocks={0}). Skipping intermediate append."
  "MergeCert.SameAsExistingSkip"             = "Output same as existing, skipped: {0}"
  "MergeCert.Done"                           = "Chain Generation Complete"
  "MergeCert.OutFile"                        = "Output File"
  "MergeCert.ChainOutFile"                   = "Chain File"
  "MergeCert.ChainCert"                      = "Chain Cert"
  "MergeCert.RootCerts"                      = "Root Certs"
  "MergeCert.PfxGenerated"                   = "PFX Generated"
  "MergeCert.PfxCopiedFromSource"            = "Decrypted and copied customer-provided PFX"
  "MergeCert.PfxCopiedAsIs"                  = "Copied customer-provided PFX as-is"
  "MergeCert.PfxFoundInSource"               = "Customer-provided PFX found: {0}"
  "MergeCert.PfxRegenPrompt"                 = "Regenerate PFX? (y/N)"
  "MergeCert.PfxRegenChosen"                 = "PFX will be regenerated."
  "MergeCert.SyncPrompt"                     = "Sync related files (.key/.csr/.tsv) to merged directory? (y/N)"
  "MergeCert.Synced"                         = "Synced: {0}"
  "MergeCert.SyncSkipped"                    = "Sync skipped."

  # Sync-ToMerged.ps1
  "SyncToMerged.KeyDecrypted"                = "(decrypted)"

  "MergeCert.ChainFromClient"                = "[INFO] Using chain from client certificate (remaining blocks)."
  "MergeCert.NoChainData"                    = "No chain data available for chainfile output."
  "MergeCert.NoCertBlock"                    = "No certificate block found in client certificate."
  "MergeCert.AutoFetchStart"                 = "[INFO] Auto-fetching issuer certificate from AIA..."
  "MergeCert.AutoFetchUrl"                   = "[INFO] AIA URL: {0}"
  "MergeCert.AutoFetchSaved"                 = "[OK] Downloaded: {0}"
  "MergeCert.AutoFetchFailed"                = "[WARN] Failed to download from AIA URL: {0}"
  "MergeCert.AutoFetchNoAia"                 = "[WARN] No AIA CA Issuers URL found in certificate: {0}"
  "MergeCert.AutoFetchNeedOpenSsl"           = "[WARN] OpenSSL not available; auto-fetch disabled."
  "MergeCert.CrossRootHint"                  = "[INFO] Cross root certificate in use ({0}); usually OK for browser trust chains."
  "MergeCert.RootDir"                        = "[DIR] RootDir: {0}"
  "MergeCert.OutDir"                         = "[DIR] OutDir : {0}"
  "MergeCert.NoTargets"                      = "[INFO] No target certificates found (.cer/.crt/.pem)"
  "MergeCert.NoIntermediateCandidates"       = "Intermediate cert not specified and no candidates found in the root directory. Specify -IntermediateCert."
  "MergeCert.MultiIntermediateMatched"       = "Multiple intermediate candidates matched (issuer/subject). To avoid wrong merge, specify -IntermediateCert.`n{0}"
  "MergeCert.NoIntermediateMatched"          = "Auto-selection failed (no candidate subject matches issuer). Aborting to avoid wrong merge.`nissuer={0}`nCandidates:`n{1}"
  "MergeCert.OneCandidateButNoVerify"        = "One intermediate candidate exists but issuer/subject verification is not possible; refusing auto-selection. Specify -IntermediateCert: {0}"
  "MergeCert.MultiCandidatesNeedSpecify"     = "Intermediate cert not specified and multiple candidates exist. To avoid wrong merge, specify -IntermediateCert.`n{0}"
  "MergeCert.RootNeedOpenSsl"                = "Cannot auto-select root/cross certificate: OpenSSL not found."
  "MergeCert.RootIssuerMissing"              = "Cannot read issuer from intermediate certificate: {0}"
  "MergeCert.MultiRootMatched"               = "Multiple root/cross candidates matched (issuer/subject). Aborting to avoid wrong merge.`n{0}"
  "MergeCert.NoRootMatched"                  = "Auto-selection failed (no candidate subject matches issuer). Aborting to avoid wrong merge.`nissuer={0}`nCandidates:`n{1}"
  "MergeCert.RootDirNotFound"                = "RootDir not found: {0}"
  "MergeCert.BatchTarget"                    = "Target: {0}"
  "MergeCert.BatchIntermediate"              = "Intermediate: {0}"
  "MergeCert.BatchIntermediateAuto"          = "(auto)"
  "MergeCert.BatchRoot"                      = "Cross-root: {0}"
  "MergeCert.BatchRootCA"                    = "Root CA: {0}"
  "MergeCert.BatchPlan"                      = "[Plan] {0}"
  "MergeCert.BatchPlanMerge2"                = "Merge 2"
  "MergeCert.BatchPlanMerge3"                = "Merge 3"
  "MergeCert.BatchPlanSkip"                  = "Skip"
  "MergeCert.BatchPrompt"                    = "Enter=continue / s=skip / q=quit"
  "MergeCert.BatchMenuTitle"                 = "Select action"
  "MergeCert.BatchMenuMerge2"                = "Merge 2"
  "MergeCert.BatchMenuMerge3"                = "Merge 3"
  "MergeCert.BatchMenuMerge3Rec"             = "Merge 3 (recommended)"
  "MergeCert.BatchMenuMerge4"                = "Merge 4 (with Root CA)"
  "MergeCert.BatchMenuSkip"                  = "Skip"
  "MergeCert.BatchMenuBack"                  = "Back"
  "MergeCert.BatchMenuQuit"                  = "Quit"
  "MergeCert.BatchCertMenuTitle"             = "Select certificate"
  "MergeCert.RootRequired"                   = "No matching root/cross certificate found for the selected merge mode."

  # Convert-KeyToPlaintext.ps1
  "DecryptKey.PathNotFound"                  = "Path not found: {0}"
  "DecryptKey.KeyHeader"                     = "[KEY] {0}"
  "DecryptKey.EncryptedLine"                 = "[INFO] Encrypted: {0}"
  "DecryptKey.SkipPlain"                     = "[SKIP] Already a plain key (no decrypt needed)"
  "DecryptKey.PassFilesLine"                 = "[PASS] Pass file({0}): {1}"
  "DecryptKey.PassEnvLine"                   = "[PASS] Env PASS_FILE: set ({0} / {1})"
  "DecryptKey.PassEnvUnset"                  = "[PASS] Env PASS_FILE: unset"
  "DecryptKey.NoPassphrase"                  = "Passphrase not found (no interactive prompt). Prepare {0} or PASS_FILE."
  "DecryptKey.InPlaceNeedOverwrite"          = "InPlace is dangerous; you must specify -Overwrite (a backup will be created)."
  "DecryptKey.BackupFailed"                  = "Failed to create backup: {0}"
  "DecryptKey.BackupLine"                    = "[BAK] Backed up original encrypted key: {0}"
  "DecryptKey.InPlaceLine"                   = "[INFO] -InPlace: output filename will not change: {0}"
  "DecryptKey.OutExistsNoOverwrite"          = "Output file already exists (overwrite blocked): {0}`nSpecify -Overwrite to overwrite."
  "DecryptKey.DecryptFailed"                 = "Decrypt failed (passphrase mismatch is likely)."
  "DecryptKey.StillEncrypted"                = "Decrypted output is still encrypted (unexpected). Check: {0}"
  "DecryptKey.Done"                          = "[OK] Decrypted key: {0}"
  "DecryptKey.NoKeys"                        = "[INFO] No target .key found"
  "DecryptKey.NgPath"                        = "[NG] {0}"
  "DecryptKey.NgMsg"                         = "[NG] {0}"

  # New-CertificateSigningRequest.ps1
  "MakeCsr.CnRequired"                       = "CN is required."
  "MakeCsr.SubjectMissing"                   = "Subject is missing. Provide -Subject, or specify all of -C/-ST/-L/-O."
  "MakeCsr.OutExistsNoOverwrite"             = "Output already has existing files (overwrite blocked): {0}`nSpecify -Overwrite to regenerate."
  "MakeCsr.PassFileUnreadable"               = "Cannot read passphrase from PassFile: {0}"
  "MakeCsr.DoneKey"                          = "[OK] Key: {0}"
  "MakeCsr.DoneCsr"                          = "[OK] CSR: {0}"
  "MakeCsr.PreviewTitle"                     = "[INFO] CSR preview (Subject / SAN)"
  "MakeCsr.SanMenuTitle"                     = "SAN Setup"
  "MakeCsr.SanMenuOptionCn"                  = "1) CN only"
  "MakeCsr.SanMenuOptionNone"                = "2) No SAN"
  "MakeCsr.SanMenuOptionDns"                 = "3) Add DNS"
  "MakeCsr.SanMenuOptionMixed"               = "4) Add DNS/IP"
  "MakeCsr.SanMenuPrompt"                    = "Select (Enter=1)"
  "MakeCsr.SanInputDns"                      = "Enter DNS (comma-separated)"
  "MakeCsr.SanInputMixed"                    = "Enter SAN (DNS:/IP: allowed, comma-separated)"

  # Export-CertificateModulus.ps1
  "ShowModulus.Title"                        = "========== Certificate / key modulus list =========="
  "ShowModulus.CreatedAt"                    = "Created at: {0}"
  "ShowModulus.SectionCert"                  = "Certificates (.cer, .crt, .pem)"
  "ShowModulus.SectionKey"                   = "Private keys (.key)"
  "ShowModulus.GroupMatch"                   = "[ MATCHED PAIR ]"
  "ShowModulus.GroupCertOnly"                = "[ ORPHAN CERTIFICATE ]"
  "ShowModulus.GroupKeyOnly"                 = "[ ORPHAN PRIVATE KEY ]"
  "ShowModulus.Calculating"                  = "Calculating Modulus..."
  "ShowModulus.ModulusHash"                  = "Modulus (SHA256): {0}"
  "ShowModulus.InvalidCert"                  = "[Invalid certificate or multiple certificates are contained in the file]"
  "ShowModulus.SkipEncryptedKey"             = "[Skipping encrypted key: prepare {0} or specify -PassFile / env PASS_FILE]"
  "ShowModulus.KeyReadError"                 = "[Failed to read key or invalid format]"
  "ShowModulus.SummaryTitle"                 = "Summary"
  "ShowModulus.SummaryCertCount"             = "Certificates processed: {0}"
  "ShowModulus.SummaryKeyCount"              = "Keys processed: {0}"
  "ShowModulus.Advice1"                      = "Compare modulus values to verify matches."
  "ShowModulus.Advice2"                      = "If cert and key modulus are identical, they are a pair."
  "ShowModulus.ConsoleTitle"                 = "[OK] Summary"
  "ShowModulus.SavedTo"                      = "Saved to: {0}"

  # Test-CertificateKeyMatch.ps1
  "VerifyMatch.ReportTitle"                  = "Certificate / key / CSR match report"
  "VerifyMatch.CreatedAt"                    = "Created at: {0}"
  "VerifyMatch.Separator"                    = "=============================================="
  "VerifyMatch.ConsoleTitle"                 = "========== Certificate / key / CSR match =========="
  "VerifyMatch.Scanning"                     = "Scanning folders (mode={0})..."
  "VerifyMatch.FolderMissing"                = "[INFO] Folder not found: {0}"
  "VerifyMatch.Checking"                     = "[{0}] Checking: {1}\\{2}\\{3}"
  "VerifyMatch.ReportHeader"                 = "[{0}] root: {1}  org: {2}  server: {3}"
  "VerifyMatch.DetectedFiles"                = "Detected files:"
  "VerifyMatch.DetectedCert"                 = "  [CERT] {0}"
  "VerifyMatch.DetectedKey"                  = "  [KEY ] {0}"
  "VerifyMatch.DetectedCsr"                  = "  [CSR ] {0}"
  "VerifyMatch.ConsoleCertMissing"           = "  Cert: missing"
  "VerifyMatch.ConsoleCertFound"             = "  Cert: found"
  "VerifyMatch.ConsoleKeyMissing"            = "  Key : missing"
  "VerifyMatch.ConsoleKeyFound"              = "  Key : found"
  "VerifyMatch.ConsoleCsrMissing"            = "  CSR : missing"
  "VerifyMatch.ConsoleCsrFound"              = "  CSR : found"
  "VerifyMatch.Judgement"                    = "--- Judgement ---"
  "VerifyMatch.NoFiles"                      = "[ERROR] No target files"
  "VerifyMatch.MatchCertKey"                 = "[OK] Cert vs Key modulus match"
  "VerifyMatch.MismatchCertKey"              = "[NG] Cert vs Key modulus mismatch"
  "VerifyMatch.MatchCertKeyDetail"           = "[OK] Cert({0}) vs Key({1}) modulus match"
  "VerifyMatch.MismatchCertKeyDetail"        = "[NG] Cert({0}) vs Key({1}) modulus mismatch"
  "VerifyMatch.MatchCertCsr"                 = "[OK] Cert vs CSR modulus match"
  "VerifyMatch.MismatchCertCsr"              = "[NG] Cert vs CSR modulus mismatch"
  "VerifyMatch.MatchCertCsrDetail"           = "[OK] Cert({0}) vs CSR({1}) modulus match"
  "VerifyMatch.MismatchCertCsrDetail"        = "[NG] Cert({0}) vs CSR({1}) modulus mismatch"
  "VerifyMatch.MatchKeyCsr"                  = "[OK] Key vs CSR modulus match"
  "VerifyMatch.MismatchKeyCsr"               = "[NG] Key vs CSR modulus mismatch"
  "VerifyMatch.MatchKeyCsrDetail"            = "[OK] Key({0}) vs CSR({1}) modulus match"
  "VerifyMatch.MismatchKeyCsrDetail"         = "[NG] Key({0}) vs CSR({1}) modulus mismatch"
  "VerifyMatch.ConsoleMatchCertKey"          = "  Cert <-> Key: match"
  "VerifyMatch.ConsoleMismatchCertKey"       = "  Cert <-> Key: mismatch"
  "VerifyMatch.ConsoleMatchCertCsr"          = "  Cert <-> CSR: match"
  "VerifyMatch.ConsoleMismatchCertCsr"       = "  Cert <-> CSR: mismatch"
  "VerifyMatch.ConsoleMatchKeyCsr"           = "  Key <-> CSR: match"
  "VerifyMatch.ConsoleMismatchKeyCsr"        = "  Key <-> CSR: mismatch"
  "VerifyMatch.ConsoleInsufficient"          = "  [WARN] Missing files required for comparison"
  "VerifyMatch.Insufficient"                 = "[WARN] Missing files required for comparison"
  "VerifyMatch.ConsoleFinalOk"               = "  Final: MATCH (valid set)"
  "VerifyMatch.ConsoleFinalNg"               = "  Final: MISMATCH (invalid set)"
  "VerifyMatch.FinalOk"                      = "[RESULT] MATCH (valid set)"
  "VerifyMatch.FinalNg"                      = "[RESULT] MISMATCH (invalid set)"
  "VerifyMatch.SummaryTitle"                 = "Summary"
  "VerifyMatch.SummaryTotal"                 = "Checked sets: {0}"
  "VerifyMatch.SummaryOk"                    = "Match (valid): {0}"
  "VerifyMatch.SummaryNg"                    = "Mismatch (invalid): {0}"
  "VerifyMatch.SavedTo"                      = "Saved to: {0}"
  "VerifyMatch.ReportSavedTo"                = "Report saved to: {0}"

  # New-CertificateSigningRequestFromOld.ps1
  "Renew.MenuTitle"                          = "Multiple organizations found. Select organizations to process."
  "Renew.MenuHint"                           = "(e.g., 1 or 1,3 / all / q)"
  "Renew.MenuPrompt"                         = "Select"
  "Renew.NoInteractive"                      = "Interactive input is not available. Specify -Org or -All."
  "Renew.Cancelled"                          = "Cancelled."
  "Renew.InvalidInput"                       = "[WARN] Invalid input. Please try again."
  "Renew.CnMissingInSubject"                 = "Cannot get CN from Subject"
  "Renew.New.NotGenerated"                   = "new=not generated"
  "Renew.New.NotGeneratedRoot"               = "new=not generated (0/{0})"
  "Renew.New.GeneratedRoot"                  = "new=generated ({0}/{1})"
  "Renew.New.GeneratedNoLatest"              = "new=generated (sets~{0}, csr={1}, key={2})"
  "Renew.New.GeneratedWithLatest"            = "new=generated (sets~{0}, csr={1}, key={2}, latest={3})"
  "Renew.OldDirMissing"                      = "OldDir does not exist: {0}"
  "Renew.RootNoCerts"                        = "No certificates directly under old; cannot select -Org (root)."
  "Renew.OrgFolderMissing"                   = "Specified org folder does not exist: {0}"
  "Renew.NoOrgFound"                         = "No org folders/certificates found under old: {0}"
  "Renew.MultiOrgNeedSpecify"                = "Multiple organizations found. Specify -Org or -All."
  "Renew.MultiOverwriteForbidden"            = "Dangerous: -Overwrite cannot be used for multiple orgs. Limit to one org with -Org."
  "Renew.MultiOverwriteWarn"                 = "[WARN] -Overwrite with multiple orgs will backup and regenerate .key/.csr files."
  "Renew.MultiOverwriteConfirmPrompt"        = "Type YES to continue"
  "Renew.CnNotFound"                         = "Cannot get CN: cert={0} subject=[{1}] csr=[{2}]"
  "Renew.BackupKeyFail"                      = "Cannot backup existing .key: {0}"
  "Renew.BackupCsrFail"                      = "Cannot backup existing .csr: {0}"
  "Renew.OutExistsNoOverwrite"               = "Output already exists (overwrite blocked): {0}`nSpecify -Overwrite to regenerate."
  "Renew.DoneTitle"                          = "Generated:"
  "Renew.ShowInfo.OpenSsl"                   = "OpenSSL: {0}"
  "Renew.ShowInfo.OldDir"                    = "OldDir : {0}"
  "Renew.ShowInfo.NewDir"                    = "NewDir : {0}"
  "Renew.ShowInfo.Version"                   = "OpenSSL version: {0}"
  "Renew.Table.Org"                          = "Organization"
  "Renew.Table.Cn"                           = "CN"
  "Renew.Table.RsaBits"                      = "Key Length"
  "Renew.Table.San"                          = "SAN"
  "Renew.Table.OutDir"                       = "Output"
  "Renew.SanMenuTitle"                       = "SAN Setup"
  "Renew.SanMenuCurrent"                     = "Current: {0}"
  "Renew.SanMenuOptionKeep"                  = "1) Use current SAN"
  "Renew.SanMenuOptionCn"                    = "2) CN only"
  "Renew.SanMenuOptionAppend"                = "3) Append"
  "Renew.SanMenuOptionReplace"               = "4) Replace"
  "Renew.SanMenuPrompt"                      = "Select (Enter=1)"
  "Renew.SanInputAppend"                     = "SAN to append (DNS:/IP: allowed, comma-separated)"
  "Renew.SanInputReplace"                    = "SAN to replace (DNS:/IP: allowed, comma-separated)"
  "Renew.OutExistsPrompt"                    = "Output files already exist. Continue?`n{0}"
  "Renew.ConflictOverwrite"                  = "Yes (overwrite and regenerate / auto backup existing)"
  "Renew.ConflictSkip"                       = "Skip this certificate, continue to next"
  "Renew.ConflictBack"                       = "Go back to previous menu"
  "Renew.ConflictCancel"                     = "No (cancel and go back)"
  "Renew.PressAnyKeyToReturn"                = "Generation complete. Press any key to return..."
  "Renew.TsvConfirmTitle"                    = "TSV Data Confirmation ({0})"
  "Renew.TsvLabelDept"                       = "Department"
  "Renew.TsvLabelOrgName"                    = "Organization"
  "Renew.TsvLabelContact"                    = "Contact"
  "Renew.TsvLabelSoftware"                   = "Software"
  "Renew.TsvExistsWarn"                      = "[WARN] TSV file already exists: {0}"
  "Renew.TsvOverwritePrompt"                 = "Overwrite? (y/N)"
  "Renew.TsvBackedUp"                        = "[INFO] Backed up existing TSV: {0}"
  "Renew.TsvAppended"                        = "[OK] Appended to TSV"
  "Renew.TsvSkipped"                         = "[SKIP] TSV output skipped"
  "Renew.TsvGenerateTitle"                   = "Generate TSV? ({0})"
  "Renew.TsvGenerateYes"                     = "Yes (generate TSV)"
  "Renew.TsvGenerateNo"                      = "No (skip TSV generation)"
  "Renew.TsvGeneratePrompt"                  = "Generate TSV? ({0}) (y/N)"

  # Matching keys
  "Matching.Title"                           = "Match Verification"
  "Matching.KeyCsr"                          = "KEY ⇔ CSR (Modulus)"
  "Matching.KeyCer"                          = "KEY ⇔ CER (Modulus)"
  "Matching.CsrTsvCn"                        = "CSR ⇔ TSV (CN)"
  "Matching.CsrTsvContent"                   = "CSR ⇔ TSV (Content)"

  # Common error messages
  "Common.FolderNotFound"                    = "[INFO] Folder not found: {0}: {1}"
  "Common.NoTargetFiles"                     = "[INFO] No target files found"
  "Common.NoCertFiles"                       = "[INFO] No certificate files (.cer/.crt/.pem) found (chain check will be skipped)"
  "Common.ErrorNg"                           = "[NG] {0}"

  # Get-CertificateInfo menu
  "CheckBasic.Menu.RootTitle"                = "Select target"
  "CheckBasic.Menu.OrgTitle"                 = "Select organization ({0})"
  "CheckBasic.Menu.CertTitle"                = "Select certificate ({0})"
  "CheckBasic.Menu.FileTitle"                = "Select file ({0})"
  "CheckBasic.Menu.Instruction"              = "Use ↑↓ / Enter to select / ESC to go back"
  "CheckBasic.Menu.NoCerts"                  = "No certificates found"
  "CheckBasic.Menu.BackPrompt"               = "Press any key to go back"

  # Test-CertificateKeyMatch.ps1 detail sections
  "VerifyMatch.Detail.CertInfo"              = "--- Certificate Info ---"
  "VerifyMatch.Detail.KeyInfo"               = "--- Private Key Info ---"
  "VerifyMatch.Detail.CsrInfo"               = "--- CSR Info ---"
  "VerifyMatch.Detail.Subject"               = "Subject:"
  "VerifyMatch.Detail.Modulus"               = "Modulus:"

  # Request-LetsEncryptCertificate.ps1
  # Request-LetsEncryptCertificate.ps1
  "LE.InputDomainPrompt"                     = "Enter the domain to issue the certificate for."
  "LE.InputEmailPrompt"                      = "Enter email address for Let's Encrypt registration."
  "LE.CommandNotFound"                       = "Command not found: {0}"
  "LE.Ready"                                 = "== Ready =="
  "LE.Domain"                                = "Domain: {0}"
  "LE.CleaningWorkDir"                       = "[INFO] Cleaning existing work directory: {0}"
  "LE.ReusingWorkDir"                        = "[INFO] Reusing existing work directory: {0}"
  "LE.ChallengeDir"                          = "Local challenge file directory:"
  "LE.ServerChallengeDir"                    = "Server challenge directory (hint):"
  "LE.ExportDir"                             = "Certificate export directory:"
  "LE.DockerMountCheck"                      = "== Docker mount self-check =="
  "LE.DockerMountFailed"                     = "Docker mount self-check failed: /work/auth.sh not visible inside container. Check Docker Desktop file sharing settings."
  "LE.StartingCertbot"                       = "== Starting certbot (Docker) =="
  "LE.CertbotFailed"                         = "certbot failed (exit code: {0}). Check logs: {1}"
  "LE.RateLimitError"                        = "[WARN] Let's Encrypt rate limit reached"
  "LE.RateLimitRetryAfter"                   = "Retry after: {0}"
  "LE.RateLimitHint"                         = "Hint: Let's Encrypt has a limit of 5 certificates per exact set of identifiers per 168 hours (7 days).`nDetails: https://letsencrypt.org/docs/rate-limits/"
  "LE.RateLimitFailed"                       = "Certificate request failed due to rate limit. Wait until the retry time above, or try a different domain."
  "LE.ErrorLogTail"                          = "Error log (last 50 lines):"
  "LE.Exporting"                             = "== Exporting certificate to host =="
  "LE.ExportFailedTrying"                    = "[WARN] Export to {0} failed, trying fallback {1}..."
  "LE.ExportFailed"                          = "Export failed: cannot write to {0} or {1}. Check Docker Desktop file sharing/security software."
  "LE.ExportDirCreateFailed"                 = "[WARN] Failed to create export directory: {0}. Fallback to: {1}"
  "LE.ExportDirFallback"                     = "[INFO] Changed export directory to: {0}"
  "LE.ExportZeroBytes"                       = "Exported file is 0 bytes ({0}={1}, {2}={3}). Check permissions/blocking."
  "LE.ExportFilesMissing"                    = "Exported files not found: {0} or {1}"
  "LE.ExportSuccess"                         = "[OK] {0} ({1} bytes)"
  "LE.CompletedMsg"                          = "Let's Encrypt certificate acquisition completed."
  "LE.PressAnyKeyToReturn"                   = "Press any key to return to menu..."

  # Request-SelfSignedCertificate.ps1
  "SS.Menu.Title"                            = "Generate 10-Year Self-Signed Certificate"
  "SS.Menu.Quick"                            = "Quick generate (from CNs in old organization certs)"
  "SS.Menu.Custom"                           = "Custom generate (set Subject and output dir)"
  "SS.Menu.QuickSelectOrg"                   = "Select Organization (Quick)"
  "SS.Menu.NoOrg"                            = "No organization folders found under old."
  "SS.Menu.NoCertInOrg"                      = "No certificate files found in selected organization: {0}"
  "SS.Prompt.CN"                             = "CN"
  "SS.Prompt.SubjectOptional"                = "Subject (optional)"
  "SS.Prompt.SANOptional"                    = "SAN (optional)"
  "SS.Prompt.OutDirOptional"                 = "Output dir (optional)"
  "SS.InputCnPrompt"                         = "Enter CN (for example: example.com)."
  "SS.InputSubjectPrompt"                    = "Enter Subject if needed (blank uses /CN=<CN>)."
  "SS.InputSanPrompt"                        = "Enter SAN if needed (blank auto-uses DNS:CN)."
  "SS.InputOutDirPrompt"                     = "Enter output directory if needed (blank uses default)."
  "SS.OpenSslNotFound"                       = "OpenSSL not found. Check the provided path or make sure openssl is available in PATH: {0}"
  "SS.OutExistsNoOverwrite"                  = "Output files already exist. Specify -Overwrite to replace them.`n{0}"
  "SS.Starting"                              = "== Generating 10-year self-signed certificate =="
  "SS.Info.CN"                               = "CN: {0}"
  "SS.Info.Subject"                          = "Subject: {0}"
  "SS.Info.SAN"                              = "SAN: {0}"
  "SS.Info.Validity"                         = "Validity: {0} days (about {1} years)"
  "SS.Info.OutDir"                           = "Output dir: {0}"
  "SS.Done.Key"                              = "[OK] Private key: {0}"
  "SS.Done.Cert"                             = "[OK] Certificate: {0}"
  "SS.Done.NotAfter"                         = "[OK] NotAfter: {0}"
  "SS.Done.Warning"                          = "[WARN] This is a self-signed certificate, not a public CA-issued certificate. Use for internal/testing purposes."
  "SS.Quick.StartOrg"                        = "== Processing organization: {0} =="
  "SS.Quick.ProcessingCert"                  = "[Processing] {0} -> CN={1}"
  "SS.Quick.CnFromCertFailed"                = "[WARN] Failed to extract CN from certificate: {0}"
  "SS.Quick.SkipDuplicateCn"                 = "[SKIP] Duplicate CN detected: {0}"
  "SS.Quick.Completed"                       = "== Organization completed: {0} =="
  "SS.Quick.SuccessCount"                    = "Success count: {0}"
  "SS.Quick.FailCount"                       = "Failure count: {0}"
  "SS.PressAnyKeyReturnOrg"                  = "Press any key to return to organization list..."

  # Repair-PemFile.ps1
  "RepairPem.ReadFailed"                     = "Failed to read file: {0}"
  "RepairPem.ZeroBytes"                      = "File is 0 bytes: {0}"
  "RepairPem.EmptyAfterBom"                  = "File is empty after BOM removal: {0}"
  "RepairPem.NoPemBlock"                     = "[{0}] No valid PEM block (BEGIN/END) found. File may not be PEM format or is corrupted: {1}"
  "RepairPem.ParseFailed"                    = "[{0}] Failed to parse PEM block: {1}"
  "RepairPem.TooShort"                       = "[{0}] PEM body too short ({1} chars), possibly truncated/corrupted: {2}"
  "RepairPem.InvalidHeader"                  = "[{0}] First line is invalid: {1}"
  "RepairPem.BackupSection"                  = "== Creating Backup =="
  "RepairPem.BackupCreated"                  = "{0} backup: {1}"
  "RepairPem.NormalizeSection"               = "== Normalizing PEM =="
  "RepairPem.VerifySection"                  = "== Verification =="
  "RepairPem.FileInfo"                       = "{0}: {1} bytes, blocks={2}, first='{3}', last='{4}'"
  "RepairPem.NginxParamsRequired"            = "-NginxExe and -NginxConf are required when using -TestNginx."
  "RepairPem.NginxTestSection"               = "== nginx -t =="
  "RepairPem.NginxTestFailed"                = "nginx -t failed (exit code: {0})"
  "RepairPem.Success"                        = "[OK] PEM file repair completed."
  "RepairPem.Failed"                         = "[FAILED] {0}"
  "RepairPem.RestoreHint"                    = "Hint: You can restore using the .bak_ timestamped file just created."

  # Install-Dependencies.ps1
  "Deps.Title"                               = "SSL Toolkit Dependency Setup"
  "Deps.AlreadyInstalled"                    = "[Installed] OpenSSL already exists: {0}"
  "Deps.Version"                             = "Version: {0}"
  "Deps.UseForceHint"                        = "To re-download, use the -Force parameter."
  "Deps.FoundSystem"                         = "[Found] OpenSSL found on system: {0}"
  "Deps.CopyToLocal"                         = "Copy it to the project-local utils/bin/ directory? (makes the project portable)"
  "Deps.CopyPrompt"                          = "Copy to local? (y/N)"
  "Deps.CopySuccess"                         = "[OK] Copied to local: {0}"
  "Deps.CopyFailed"                          = "[FAILED] Copied OpenSSL is not working."
  "Deps.Downloading"                         = "[Download] Trying to download portable OpenSSL..."
  "Deps.TryingSource"                        = "[Trying] Source: {0}"
  "Deps.DownloadTooSmall"                    = "[Warning] Downloaded file is too small, possibly invalid."
  "Deps.Extracting"                          = "[Extract] Extracting..."
  "Deps.OpenSslNotFoundInArchive"            = "[Warning] openssl.exe not found in archive."
  "Deps.ExtractedButNotWorking"              = "[Warning] Extracted but OpenSSL is not working."
  "Deps.DownloadFailed"                      = "[FAILED] Download failed: {0}"
  "Deps.InstallSuccess"                      = "[OK] OpenSSL installation complete!"
  "Deps.InstalledTo"                         = "Installed to: {0}"
  "Deps.AutoFailed"                          = "[FAILED] Automatic download did not succeed. Please install manually:"
  "Deps.ManualGuide"                         = "Manual installation guide:"
  "Deps.ManualStep1"                         = "  1. Download Win64 OpenSSL from https://slproweb.com/products/Win32OpenSSL.html"
  "Deps.ManualStep2"                         = "  2. Copy openssl.exe and related DLLs to: {0}"
  "Deps.ManualStep3"                         = "  3. Or install Git for Windows (includes OpenSSL)"
  "Deps.ManualAlt1"                          = "Alternative: winget install ShiningLight.OpenSSL"
  "Deps.ManualAlt2"                          = "Alternative: Install Git for Windows (https://git-scm.com/)"
}
