@{
  # Language metadata
  "Language.DisplayName"                     = "中文"
  "Language.VersionCheckError"               = "[错误] 需要 PowerShell 7.x 以上版本。"
  "Language.VersionCheckCurrent"             = "当前版本"

  # Common
  "Common.Yes"                               = "是"
  "Common.No"                                = "否"
  "Common.Success"                           = "成功"
  "Common.Failed"                            = "失败"
  "Common.Skip"                              = "跳过"
  "Common.Info"                              = "信息"
  "Common.Warn"                              = "警告"
  "Common.MenuCancel"                        = "取消"
  "Common.MenuAll"                           = "全部"
  "Common.MenuQuit"                          = "退出"
  "Common.Cancelled"                         = "操作已取消"
  "Common.Welcome"                           = "SSL证书管理工具"
  "Common.PressAnyKey"                       = "按任意键继续..."
  "Toolkit.ExitConfirmation"                 = "即将退出。按任意键关闭窗口..."
  "Common.Prompt.Domain"                     = "域名"
  "Common.Prompt.Email"                      = "电子邮件"

  "Toolkit.Banner.Title"                     = "SSL 证书管理工具"
  "Toolkit.Banner.Version"                   = "Ver {0}  https://github.com/sunshaoxuan"
  "Toolkit.Exit.VersionLine"                 = "版本: {0}"
  "Toolkit.Exit.UpdatedLine"                 = "最后更新: {0}"
  "Toolkit.Exit.Copyright"                   = "Copyright (c) sunshaoxuan"
  "Toolkit.Exit.Thanks"                      = "感谢您的使用！"

  # Toolkit menu
  "Toolkit.Menu.Title"                       = "请选择工具 (↑↓选择, Enter确认, ESC退出)"
  "Toolkit.Menu.Exit"                        = "[ 退出 ]"
  "Toolkit.Menu.Back"                        = "[ 返回 ]"
  "Toolkit.Menu.Language"                    = "语言"
  "Toolkit.Menu.SelectLanguage"              = "选择显示语言"
  "Toolkit.Menu.SubMenuSelect"               = "{0} - 请选择类型"
  "Toolkit.Menu.Starting"                    = "正在启动: {0}"
  "Toolkit.Menu.PressAnyKey"                 = "按任意键返回菜单..."
  "Toolkit.Menu.AutoRename"                  = "启动时自动执行：组织文件夹重命名检查..."
  "Toolkit.Menu.AutoRenameFailed"            = "自动重命名检查失败，已跳过: {0}"
  "Toolkit.Menu.ScriptNotFound"              = "脚本未找到: {0}"

  # Tool descriptions
  "Toolkit.Tool.CertInfo"                    = "查看证书信息"
  "Toolkit.Tool.CsrFromOld"                  = "从旧证书续期CSR"
  "Toolkit.Tool.NewCsr"                      = "创建新CSR"
  "Toolkit.Tool.MergeChain"                  = "合并证书链"
  "Toolkit.Tool.ConvertKey"                  = "密钥转换为明文"
  "Toolkit.Tool.ExportModulus"               = "导出证书模数"
  "Toolkit.Tool.RepairPem"                   = "修复PEM文件"
  "Toolkit.Tool.ServerList"                  = "导出证书更新清单（TSV）"
  "Toolkit.Tool.SyncMerged"                  = "同步到output/merged (key,csr,tsv)"
  "Toolkit.Tool.SelfSigned"                  = "自签证书"
  "Toolkit.SubTool.SelfSigned"               = "生成自签证书"
  "Toolkit.SubTool.SelfSigned10Y"            = "生成10年期自签证书"
  "Toolkit.SubTool.LetsEncrypt"              = "获取 Let's Encrypt 证书"
  "Common.FileNotFound"                      = "{0} 不存在: {1}"
  "Common.OpenSslCmdFailed"                  = "OpenSSL 命令失败: {0}`n{1}"
  "Common.Exists"                            = "存在"
  "Common.NotExists"                         = "不存在"
  "Common.I18nModuleNotFound"                = "找不到 i18n 模块: {0}"
  "Common.DirNotFound"                       = "{0} 不存在: {1}"

  # Common labels
  "Label.Old"                                = "旧"
  "Label.New"                                = "新"
  "Label.Merged"                             = "已合并"
  "Label.SelfSigned"                         = "自签"
  "Label.Cert"                               = "证书"
  "Label.Csr"                                = "申请(CSR)"
  "Label.Key"                                = "私钥"
  "Label.File"                               = "文件"
  "Label.FileType"                           = "类型"
  "Label.Format"                             = "格式"
  "Label.Blocks"                             = "证书块数"
  "Label.HasChain"                           = "中间证书同梱"
  "Label.FinalUse"                           = "最终用途"
  "Label.ExtChainCand"                       = "外部中间证书(候选)"
  "Label.Encrypted"                          = "加密"
  "Label.PassFile"                           = "密码文件"
  "Label.AutoMode"                           = "无人值守"
  "Label.DecryptCheck"                       = "解密检查"
  "Label.OpenSslDetails"                     = "OpenSSL 详细信息"
  "Label.ChainBlockServer"                   = "服务器证书"
  "Label.ChainBlockIntermediate"             = "中间CA证书"
  "Label.ChainBlockRoot"                     = "根/交叉根证书"
  "Label.Subject"                            = "Subject"
  "Label.Issuer"                             = "Issuer"
  "Label.NotBefore"                          = "有效期(开始)"
  "Label.NotAfter"                           = "有效期(结束)"
  "Label.TimeZone"                           = "时区"
  "Label.GmtOriginal"                        = "GMT原文"
  "Common.MenuBack"                          = "返回"

  # Get-CertificateInfo.ps1
  "CheckBasic.Header"                        = "========== {0} =========="
  "CheckBasic.Dir"                           = "[DIR] {0}"
  "CheckBasic.PassFilePresent"               = "密码:{0}"
  "CheckBasic.PassFileMissing"               = "密码:{0} 无"
  "CheckBasic.PassEnvPresent"                = "PASS_FILE:有"
  "CheckBasic.PassEnvMissingFile"            = "PASS_FILE:文件不存在"
  "CheckBasic.None"                          = "(无)"
  "CheckBasic.NotFound"                      = "未发现"
  "CheckBasic.Cert.NotMerged"                = "未合并"
  "CheckBasic.Cert.NeedMerge"                = "需合并"
  "CheckBasic.Cert.Candidate"                = "候选:{0}"
  "CheckBasic.Cert.Issuer"                   = "发证机构:{0}"
  "CheckBasic.Cert.HasChain"                 = "已含中间证书"
  "CheckBasic.Cert.UsableGuess"              = "可用(推测)"
  "CheckBasic.Cert.Unk"                      = "未知"
  "CheckBasic.Cert.FormatUnknown"            = "未知"
  "CheckBasic.Cert.Expiry"                   = "到期:{0}"
  "CheckBasic.Cert.ChainFile"                = "链文件"
  "CheckBasic.Cert.ChainBlocks"              = "链块数"
  "CheckBasic.Cert.ChainFormat"              = "链格式"
  "CheckBasic.Cert.ChainFileBlocks"          = "链:{0}"
  "CheckBasic.Cert.ChainFileFound"           = "链:已发现"
  "CheckBasic.Cert.SAN"                      = "SAN"
  "CheckBasic.ChainFileIgnored"              = "[信息] -ChainFile 仅在 -Path 时有效，已忽略。"
  "CheckBasic.Pretty.CertTitle"              = "证书"
  "CheckBasic.Pretty.CsrTitle"               = "CSR"
  "CheckBasic.Pretty.KeyTitle"               = "私钥"
  "CheckBasic.Pretty.Path"                   = "路径"
  "CheckBasic.Pretty.File"                   = "文件"
  "CheckBasic.Pretty.Expiry"                 = "到期"
  "CheckBasic.Pretty.Chain"                  = "链"
  "CheckBasic.Pretty.ChainFile"              = "链文件"
  "CheckBasic.Pretty.Blocks"                 = "证书块"
  "CheckBasic.Pretty.ChainBlocks"            = "链块"
  "CheckBasic.Pretty.Issuer"                 = "颁发者"
  "CheckBasic.Pretty.Format"                 = "格式"
  "CheckBasic.Pretty.Subject"                = "主题"
  "CheckBasic.Pretty.SAN"                    = "SAN"
  "CheckBasic.Pretty.Encrypted"              = "加密"
  "CheckBasic.Pretty.AutoMode"               = "无人值守"
  "CheckBasic.Pretty.Decrypt"                = "解密"
  "CheckBasic.Key.Encrypted"                 = "已加密"
  "CheckBasic.Key.Plain"                     = "明文"
  "CheckBasic.Key.DecOk"                     = "解密:成功"
  "CheckBasic.Key.DecFail"                   = "解密:失败"
  "CheckBasic.Key.DecSkip"                   = "解密:{0}"
  "CheckBasic.Key.AutoOkNoPass"              = "可无人执行（无需密码）"
  "CheckBasic.Key.AutoOkNeedPass"            = "可无人执行（需解密 / 无交互）"
  "CheckBasic.Key.AutoNgNeedPass"            = "不可无人执行（无密码且禁止交互）"
  "CheckBasic.Key.SkipNoPass"                = "跳过(无密码)"
  "CheckBasic.Key.SkipNoPassLong"            = "跳过（无密码）"

  # Detail mode labels (Get-CertificateInfo.ps1)
  "CheckBasic.Detail.File"                   = "[FILE] {0}"
  "CheckBasic.Detail.Key"                    = "[KEY]"
  "CheckBasic.Detail.Key.Encrypted"          = "[KEY] 加密: {0}"
  "CheckBasic.Detail.Key.PassFile"           = "[KEY] 密码文件({0}): {1}"
  "CheckBasic.Detail.Key.EnvPassSet"         = "[KEY] 环境变量 PASS_FILE: 已设置（{0} / {1}）"
  "CheckBasic.Detail.Key.EnvPassUnset"       = "[KEY] 环境变量 PASS_FILE: 未设置"
  "CheckBasic.Detail.Key.Auto"               = "[KEY] 无人执行: {0}"
  "CheckBasic.Detail.Key.DecCheck"           = "[KEY] 解密检查: {0}"
  "CheckBasic.Detail.Subject"                = "主题:"
  "CheckBasic.Detail.SAN"                    = "SAN:"
  "CheckBasic.Detail.Key.CannotReadNeedPass" = "[警告] 加密私钥无法读取（请准备 {0} 或 -PassFile / 环境变量 PASS_FILE）"
  "CheckBasic.Detail.Key.CannotRead"         = "[警告] 无法读取私钥"
  "CheckBasic.Detail.UnsupportedExt"         = "不支持的扩展名: {0}"
  "CheckBasic.Detail.Cert.HasPrivateKey"     = "包含私钥"
  "CheckBasic.Detail.Cert.NoChainHint"       = "[证书] 备注: 未包含中间证书。如需合并请使用 Merge-CertificateChain.ps1 等。"

  # Merge-CertificateChain.ps1
  "MergeCert.TitleSingle"                    = "证书链合并工具"
  "MergeCert.TitleBatch"                     = "证书链合并工具（批量）"
  "MergeCert.Step1"                          = "输入文件检查"
  "MergeCert.Step2"                          = "统一换行并合并"
  "MergeCert.ClientCert"                     = "客户端证书"
  "MergeCert.IntermediateCert"               = "中间证书(CA)"
  "MergeCert.AlreadyHasChain"                = "证书可能已包含链（CERT 块数={0}），不再追加中间证书。"
  "MergeCert.SameAsExistingSkip"             = "输出文件内容一致，跳过: {0}"
  "MergeCert.Done"                           = "已生成证书链"
  "MergeCert.OutFile"                        = "输出文件"
  "MergeCert.ChainOutFile"                   = "链文件"
  "MergeCert.ChainCert"                      = "链证书"
  "MergeCert.RootCerts"                      = "根证书"
  "MergeCert.PfxGenerated"                   = "已生成 PFX"
  "MergeCert.PfxCopiedFromSource"            = "已解密并复制客户提供的 PFX"
  "MergeCert.PfxCopiedAsIs"                  = "已原样复制客户提供的 PFX"
  "MergeCert.PfxFoundInSource"               = "发现客户提供的 PFX: {0}"
  "MergeCert.PfxRegenPrompt"                 = "是否重新生成 PFX？(y/N)"
  "MergeCert.PfxRegenChosen"                 = "将重新生成 PFX。"
  "MergeCert.SyncPrompt"                     = "是否同步其他文件(.key/.csr/.tsv)到合并目录？(y/N)"
  "MergeCert.Synced"                         = "已同步: {0}"
  "MergeCert.SyncSkipped"                    = "已跳过同步。"

  # Sync-ToMerged.ps1
  "SyncToMerged.KeyDecrypted"                = "(已解密)"

  "MergeCert.ChainFromClient"                = "[信息] 使用客户端证书中的剩余区块作为链。"
  "MergeCert.NoChainData"                    = "没有可用于链文件的证书数据。"
  "MergeCert.NoCertBlock"                    = "客户端证书中未找到 CERT 区块。"
  "MergeCert.AutoFetchStart"                 = "[信息] 正在从 AIA 自动获取颁发者证书..."
  "MergeCert.AutoFetchUrl"                   = "[信息] AIA URL: {0}"
  "MergeCert.AutoFetchSaved"                 = "[成功] 下载完成: {0}"
  "MergeCert.AutoFetchFailed"                = "[警告] 无法从 AIA URL 获取: {0}"
  "MergeCert.AutoFetchNoAia"                 = "[警告] 证书中未找到 AIA (CA Issuers) URL: {0}"
  "MergeCert.AutoFetchNeedOpenSsl"           = "[警告] 未找到 OpenSSL，已禁用自动获取。"
  "MergeCert.CrossRootHint"                  = "[信息] 当前使用交叉根证书（{0}），通常不会影响浏览器信任链。"
  "MergeCert.RootDir"                        = "[DIR] RootDir: {0}"
  "MergeCert.OutDir"                         = "[DIR] OutDir : {0}"
  "MergeCert.NoTargets"                      = "[信息] 未找到目标证书(.cer/.crt/.pem)"
  "MergeCert.NoIntermediateCandidates"       = "未指定中间证书，且根目录未找到候选文件。请指定 -IntermediateCert。"
  "MergeCert.MultiIntermediateMatched"       = "中间证书候选出现多条匹配（issuer/subject）。为避免误合并，请指定 -IntermediateCert。`n{0}"
  "MergeCert.NoIntermediateMatched"          = "自动选择中间证书失败（issuer 与 candidate subject 不匹配）。为避免误合并已中止。`nissuer={0}`n候选:`n{1}"
  "MergeCert.OneCandidateButNoVerify"        = "存在 1 个中间证书候选，但无法验证 issuer/subject 一致性，拒绝自动选择。请明确指定 -IntermediateCert: {0}"
  "MergeCert.MultiCandidatesNeedSpecify"     = "未指定中间证书且候选有多个。为避免误合并，请指定 -IntermediateCert。`n{0}"
  "MergeCert.RootNeedOpenSsl"                = "无法自动选择根/交叉证书：未找到 OpenSSL。"
  "MergeCert.RootIssuerMissing"              = "无法获取中间证书 issuer: {0}"
  "MergeCert.MultiRootMatched"               = "根/交叉证书候选出现多条匹配（issuer/subject）。为避免误合并已中止。`n{0}"
  "MergeCert.NoRootMatched"                  = "自动选择根/交叉证书失败（issuer 与 candidate subject 不匹配）。为避免误合并已中止。`nissuer={0}`n候选:`n{1}"
  "MergeCert.RootDirNotFound"                = "RootDir 不存在: {0}"
  "MergeCert.BatchTarget"                    = "对象: {0}"
  "MergeCert.BatchIntermediate"              = "中间: {0}"
  "MergeCert.BatchIntermediateAuto"          = "(自动选择)"
  "MergeCert.BatchRoot"                      = "交叉根: {0}"
  "MergeCert.BatchRootCA"                    = "根CA: {0}"
  "MergeCert.BatchPlan"                      = "[计划] {0}"
  "MergeCert.BatchPlanMerge2"                = "2 张合并"
  "MergeCert.BatchPlanMerge3"                = "3 张合并"
  "MergeCert.BatchPlanSkip"                  = "跳过"
  "MergeCert.BatchPrompt"                    = "回车继续 / s 跳过 / q 退出"
  "MergeCert.BatchMenuTitle"                 = "请选择操作"
  "MergeCert.BatchMenuMerge2"                = "2 张合并"
  "MergeCert.BatchMenuMerge3"                = "3 张合并"
  "MergeCert.BatchMenuMerge3Rec"             = "3 张合并(推荐)"
  "MergeCert.BatchMenuMerge4"                = "4 张合并（含根CA）"
  "MergeCert.BatchMenuSkip"                  = "跳过"
  "MergeCert.BatchMenuBack"                  = "返回"
  "MergeCert.BatchMenuQuit"                  = "退出"
  "MergeCert.BatchCertMenuTitle"             = "请选择证书"
  "MergeCert.RootRequired"                   = "所选合并模式未找到匹配的根/交叉证书。"

  # Convert-KeyToPlaintext.ps1
  "DecryptKey.PathNotFound"                  = "路径不存在: {0}"
  "DecryptKey.KeyHeader"                     = "[私钥] {0}"
  "DecryptKey.EncryptedLine"                 = "[信息] 加密: {0}"
  "DecryptKey.SkipPlain"                     = "[跳过] 已是明文私钥（无需解密）"
  "DecryptKey.PassFilesLine"                 = "[PASS] 密码文件({0}): {1}"
  "DecryptKey.PassEnvLine"                   = "[PASS] 环境变量 PASS_FILE: 已设置（{0} / {1}）"
  "DecryptKey.PassEnvUnset"                  = "[PASS] 环境变量 PASS_FILE: 未设置"
  "DecryptKey.NoPassphrase"                  = "未找到密码（不进行交互输入）。请准备 {0} 或 PASS_FILE。"
  "DecryptKey.InPlaceNeedOverwrite"          = "InPlace 风险较高，必须指定 -Overwrite（会创建备份）。"
  "DecryptKey.WhatThisDoes"                  = "[信息] 这个工具会把“加密的私钥”转换成“无需密码、可直接部署的 key 文件”。"
  "DecryptKey.OutputLine"                    = "[信息] 输出路径: {0}"
  "DecryptKey.InPlaceWillReplace"            = "[信息] 使用 -InPlace 时，会先创建备份，再用解密后的内容替换原 key 文件。"
  "DecryptKey.InPlaceConfirmPrompt"          = "是否用解密后的内容替换原 key 文件？ [Y/N]"
  "DecryptKey.OutExistsConfirmPrompt"        = "是否先备份再覆盖已有输出文件？ [Y/N]"
  "DecryptKey.BackupLineOut"                 = "[BAK] 已备份已有输出文件: {0}"
  "DecryptKey.SkipByUser"                    = "[跳过] 根据用户选择，已取消当前私钥的转换"
  "DecryptKey.BackupFailed"                  = "创建备份失败: {0}"
  "DecryptKey.BackupLine"                    = "[BAK] 已备份原加密 key: {0}"
  "DecryptKey.InPlaceLine"                   = "[信息] 使用 -InPlace，解密后文件名保持不变: {0}"
  "DecryptKey.OutExistsNoOverwrite"          = "输出文件已存在（防止覆盖）: {0}`n如需覆盖请指定 -Overwrite。"
  "DecryptKey.DecryptFailed"                 = "解密失败（可能密码不匹配）。"
  "DecryptKey.StillEncrypted"                = "解密结果仍为加密状态（异常）。请检查输出: {0}"
  "DecryptKey.Done"                          = "[成功] 解密 key: {0}"
  "DecryptKey.NoKeys"                        = "[信息] 未找到目标 .key"
  "DecryptKey.NgPath"                        = "[失败] {0}"
  "DecryptKey.NgMsg"                         = "[失败] {0}"

  # New-CertificateSigningRequest.ps1
  "MakeCsr.CnRequired"                       = "CN 为必填。"
  "MakeCsr.SubjectMissing"                   = "未指定 Subject。请提供 -Subject，或完整指定 -C/-ST/-L/-O。"
  "MakeCsr.OutExistsNoOverwrite"             = "输出目录已存在同名文件（防止覆盖）: {0}`n如需重新生成请指定 -Overwrite。"
  "MakeCsr.PassFileUnreadable"               = "无法从 PassFile 读取密码: {0}"
  "MakeCsr.DoneKey"                          = "[成功] 私钥: {0}"
  "MakeCsr.DoneCsr"                          = "[成功] CSR : {0}"
  "MakeCsr.PreviewTitle"                     = "[信息] CSR 预览（Subject / SAN）"
  "MakeCsr.SanMenuTitle"                     = "SAN 设置"
  "MakeCsr.SanMenuOptionCn"                  = "1) 仅 CN"
  "MakeCsr.SanMenuOptionNone"                = "2) 无 SAN"
  "MakeCsr.SanMenuOptionDns"                 = "3) 添加 DNS"
  "MakeCsr.SanMenuOptionMixed"               = "4) 添加 DNS/IP"
  "MakeCsr.SanMenuPrompt"                    = "选择 (Enter=1)"
  "MakeCsr.SanInputDns"                      = "输入 DNS（逗号分隔）"
  "MakeCsr.SanInputMixed"                    = "输入 SAN（可用 DNS:/IP: 前缀，逗号分隔）"

  # Export-CertificateModulus.ps1
  "ShowModulus.Title"                        = "========== 证书/私钥 Modulus 列表 =========="
  "ShowModulus.CreatedAt"                    = "生成时间: {0}"
  "ShowModulus.SectionCert"                  = "证书 (.cer, .crt, .pem)"
  "ShowModulus.SectionKey"                   = "私钥 (.key)"
  "ShowModulus.GroupMatch"                   = "【完全匹配 (Matched)】"
  "ShowModulus.GroupCertOnly"                = "【仅证书 (Cert Only)】"
  "ShowModulus.GroupKeyOnly"                 = "【仅私钥 (Key Only)】"
  "ShowModulus.Calculating"                  = "正在计算 Modulus..."
  "ShowModulus.ModulusHash"                  = "Modulus (SHA256): {0}"
  "ShowModulus.InvalidCert"                  = "[证书无效，或文件内包含多个证书块]"
  "ShowModulus.SkipEncryptedKey"             = "[因私钥已加密而跳过: 请准备 {0} 或指定 -PassFile / 环境变量 PASS_FILE]"
  "ShowModulus.KeyReadError"                 = "[读取私钥失败或格式不正确]"
  "ShowModulus.SummaryTitle"                 = "概要"
  "ShowModulus.SummaryCertCount"             = "处理的证书数: {0}"
  "ShowModulus.SummaryKeyCount"              = "处理的私钥数: {0}"
  "ShowModulus.Advice1"                      = "请通过对比 Modulus 值确认是否匹配。"
  "ShowModulus.Advice2"                      = "证书与私钥 Modulus 一致则为一对。"
  "ShowModulus.ConsoleTitle"                 = "[成功] 概要"
  "ShowModulus.SavedTo"                      = "保存到: {0}"

  # Test-CertificateKeyMatch.ps1
  "VerifyMatch.ReportTitle"                  = "证书/私钥/CSR 一致性验证报告"
  "VerifyMatch.CreatedAt"                    = "生成时间: {0}"
  "VerifyMatch.Separator"                    = "=============================================="
  "VerifyMatch.ConsoleTitle"                 = "========== 证书/私钥/CSR 一致性验证 =========="
  "VerifyMatch.Scanning"                     = "正在扫描文件夹（模式={0}）..."
  "VerifyMatch.FolderMissing"                = "[信息] 文件夹不存在: {0}"
  "VerifyMatch.Checking"                     = "[{0}] 检查中: {1}\\{2}\\{3}"
  "VerifyMatch.ReportHeader"                 = "[{0}] 根: {1}  机构: {2}  服务: {3}"
  "VerifyMatch.DetectedFiles"                = "发现文件:"
  "VerifyMatch.DetectedCert"                 = "  [证书] {0}"
  "VerifyMatch.DetectedKey"                  = "  [私钥] {0}"
  "VerifyMatch.DetectedCsr"                  = "  [CSR ] {0}"
  "VerifyMatch.ConsoleCertMissing"           = "  证书: 无"
  "VerifyMatch.ConsoleCertFound"             = "  证书: 有"
  "VerifyMatch.ConsoleKeyMissing"            = "  私钥: 无"
  "VerifyMatch.ConsoleKeyFound"              = "  私钥: 有"
  "VerifyMatch.ConsoleCsrMissing"            = "  CSR : 无"
  "VerifyMatch.ConsoleCsrFound"              = "  CSR : 有"
  "VerifyMatch.Judgement"                    = "--- 判定 ---"
  "VerifyMatch.NoFiles"                      = "[错误] 没有目标文件"
  "VerifyMatch.MatchCertKey"                 = "[成功] 证书 与 私钥 Modulus 一致"
  "VerifyMatch.MismatchCertKey"              = "[错误] 证书 与 私钥 Modulus 不一致"
  "VerifyMatch.MatchCertKeyDetail"           = "[成功] 证书({0}) 与 私钥({1}) Modulus 一致"
  "VerifyMatch.MismatchCertKeyDetail"        = "[错误] 证书({0}) 与 私钥({1}) Modulus 不一致"
  "VerifyMatch.MatchCertCsr"                 = "[成功] 证书 与 CSR Modulus 一致"
  "VerifyMatch.MismatchCertCsr"              = "[错误] 证书 与 CSR Modulus 不一致"
  "VerifyMatch.MatchCertCsrDetail"           = "[成功] 证书({0}) 与 CSR({1}) Modulus 一致"
  "VerifyMatch.MismatchCertCsrDetail"        = "[错误] 证书({0}) 与 CSR({1}) Modulus 不一致"
  "VerifyMatch.MatchKeyCsr"                  = "[成功] 私钥 与 CSR Modulus 一致"
  "VerifyMatch.MismatchKeyCsr"               = "[错误] 私钥 与 CSR Modulus 不一致"
  "VerifyMatch.MatchKeyCsrDetail"            = "[成功] 私钥({0}) 与 CSR({1}) Modulus 一致"
  "VerifyMatch.MismatchKeyCsrDetail"         = "[错误] 私钥({0}) 与 CSR({1}) Modulus 不一致"
  "VerifyMatch.ConsoleMatchCertKey"          = "  证书 <-> 私钥: 一致"
  "VerifyMatch.ConsoleMismatchCertKey"       = "  证书 <-> 私钥: 不一致"
  "VerifyMatch.ConsoleMatchCertCsr"          = "  证书 <-> CSR: 一致"
  "VerifyMatch.ConsoleMismatchCertCsr"       = "  证书 <-> CSR: 不一致"
  "VerifyMatch.ConsoleMatchKeyCsr"           = "  私钥 <-> CSR: 一致"
  "VerifyMatch.ConsoleMismatchKeyCsr"        = "  私钥 <-> CSR: 不一致"
  "VerifyMatch.ConsoleInsufficient"          = "  [警告] 缺少对比所需的文件"
  "VerifyMatch.Insufficient"                 = "[警告] 缺少对比所需的文件"
  "VerifyMatch.ConsoleFinalOk"               = "  最终结果: 一致（有效）"
  "VerifyMatch.ConsoleFinalNg"               = "  最终结果: 不一致（无效）"
  "VerifyMatch.FinalOk"                      = "[结果] 一致（有效）"
  "VerifyMatch.FinalNg"                      = "[结果] 不一致（无效）"
  "VerifyMatch.SummaryTitle"                 = "概要"
  "VerifyMatch.SummaryTotal"                 = "检查数量: {0}"
  "VerifyMatch.SummaryOk"                    = "一致（有效）: {0}"
  "VerifyMatch.SummaryNg"                    = "不一致（无效）: {0}"
  "VerifyMatch.SavedTo"                      = "保存到: {0}"
  "VerifyMatch.ReportSavedTo"                = "报告保存到: {0}"

  # New-CertificateSigningRequestFromOld.ps1
  "Renew.MenuTitle"                          = "发现多个机构，请选择要处理的机构。"
  "Renew.MenuHint"                           = "（例: 1 或 1,3 / all / q）"
  "Renew.MenuPrompt"                         = "选择"
  "Renew.NoInteractive"                      = "当前环境无法进行交互输入。请用 -Org 指定机构，或指定 -All。"
  "Renew.Cancelled"                          = "已取消。"
  "Renew.InvalidInput"                       = "[警告] 输入无效，请重新输入。"
  "Renew.CnMissingInSubject"                 = "无法从 Subject 获取 CN"
  "Renew.New.NotGenerated"                   = "new=未生成"
  "Renew.New.NotGeneratedRoot"               = "new=未生成 (0/{0})"
  "Renew.New.GeneratedRoot"                  = "new=已生成 ({0}/{1})"
  "Renew.New.GeneratedNoLatest"              = "new=已生成 (sets~{0}, csr={1}, key={2})"
  "Renew.New.GeneratedWithLatest"            = "new=已生成 (sets~{0}, csr={1}, key={2}, latest={3})"
  "Renew.OldDirMissing"                      = "OldDir 不存在: {0}"
  "Renew.RootNoCerts"                        = "old 根目录没有证书，无法选择 -Org (root)。"
  "Renew.OrgFolderMissing"                   = "指定的机构文件夹不存在: {0}"
  "Renew.NoOrgFound"                         = "old 目录下未找到机构文件夹/证书: {0}"
  "Renew.MultiOrgNeedSpecify"                = "发现多个机构，请用 -Org 指定，或指定 -All。"
  "Renew.MultiOverwriteForbidden"            = "危险操作：不允许对多个机构使用 -Overwrite。请用 -Org 限定到单个机构。"
  "Renew.MultiOverwriteWarn"                 = "[警告] 选择多个机构且指定了 -Overwrite，将备份并重新生成 .key/.csr。"
  "Renew.MultiOverwriteConfirmPrompt"        = "继续请输入 YES"
  "Renew.CnNotFound"                         = "无法获取 CN: cert={0} subject=[{1}] csr=[{2}]"
  "Renew.BackupKeyFail"                      = "无法备份既存 .key: {0}"
  "Renew.BackupCsrFail"                      = "无法备份既存 .csr: {0}"
  "Renew.OutExistsNoOverwrite"               = "输出已存在（防止覆盖）: {0}`n如需重新生成请指定 -Overwrite。"
  "Renew.DoneTitle"                          = "生成完成:"
  "Renew.ShowInfo.OpenSsl"                   = "OpenSSL: {0}"
  "Renew.ShowInfo.OldDir"                    = "OldDir : {0}"
  "Renew.ShowInfo.NewDir"                    = "NewDir : {0}"
  "Renew.ShowInfo.Version"                   = "OpenSSL version: {0}"
  "Renew.Table.Org"                          = "机构"
  "Renew.Table.Cn"                           = "CN"
  "Renew.Table.RsaBits"                      = "密钥长度"
  "Renew.Table.San"                          = "SAN"
  "Renew.Table.OutDir"                       = "输出目录"
  "Renew.SanMenuTitle"                       = "SAN 设置"
  "Renew.SanMenuCurrent"                     = "当前: {0}"
  "Renew.SanMenuOptionKeep"                  = "1) 使用当前 SAN"
  "Renew.SanMenuOptionCn"                    = "2) 仅 CN"
  "Renew.SanMenuOptionAppend"                = "3) 追加"
  "Renew.SanMenuOptionReplace"               = "4) 替换"
  "Renew.SanMenuPrompt"                      = "选择 (Enter=1)"
  "Renew.SanInputAppend"                     = "追加 SAN（可用 DNS:/IP: 前缀，逗号分隔）"
  "Renew.SanInputReplace"                    = "替换 SAN（可用 DNS:/IP: 前缀，逗号分隔）"
  "Renew.OutExistsPrompt"                    = "输出目录已存在文件。是否继续？`n{0}"
  "Renew.ConflictOverwrite"                  = "是 (覆盖重新生成 / 旧文件自动备份)"
  "Renew.ConflictSkip"                       = "跳过此证书，处理下一个"
  "Renew.ConflictBack"                       = "返回上级菜单"
  "Renew.ConflictCancel"                     = "否 (中止并返回)"
  "Renew.PressAnyKeyToReturn"                = "生成完成。按任意键返回菜单..."
  "Renew.TsvConfirmTitle"                    = "TSV 数据确认 ({0})"
  "Renew.TsvLabelDept"                       = "部门"
  "Renew.TsvLabelOrgName"                    = "机构名"
  "Renew.TsvLabelContact"                    = "负责人"
  "Renew.TsvLabelSoftware"                   = "软件"
  "Renew.TsvExistsWarn"                      = "[警告] TSV 文件已存在: {0}"
  "Renew.TsvOverwritePrompt"                 = "是否覆盖？ (y/N)"
  "Renew.TsvBackedUp"                        = "[信息] 已备份现有 TSV: {0}"
  "Renew.TsvAppended"                        = "[成功] 已追加到 TSV"
  "Renew.TsvSkipped"                         = "[跳过] TSV 输出已跳过"
  "Renew.TsvGenerateTitle"                   = "是否生成 TSV？ ({0})"
  "Renew.TsvGenerateYes"                     = "是（生成 TSV）"
  "Renew.TsvGenerateNo"                      = "否（不生成 TSV）"
  "Renew.TsvGeneratePrompt"                  = "是否生成 TSV？ ({0}) (y/N)"

  # Matching keys
  "Matching.Title"                           = "一致性验证"
  "Matching.KeyCsr"                          = "KEY ⇔ CSR (模数)"
  "Matching.KeyCer"                          = "KEY ⇔ CER (模数)"
  "Matching.CsrTsvCn"                        = "CSR ⇔ TSV (CN)"
  "Matching.CsrTsvContent"                   = "CSR ⇔ TSV (内容)"

  # Common error messages
  "Common.FolderNotFound"                    = "[信息] {0} 文件夹不存在: {1}"
  "Common.NoTargetFiles"                     = "[信息] 未找到目标文件"
  "Common.NoCertFiles"                       = "[信息] 未找到证书文件(.cer/.crt/.pem)（将不执行中间证书合并检查）"
  "Common.ErrorNg"                           = "[失败] {0}"

  # Get-CertificateInfo menu
  "CheckBasic.Menu.RootTitle"                = "选择显示范围"
  "CheckBasic.Menu.OrgTitle"                 = "选择机构（{0}）"
  "CheckBasic.Menu.CertTitle"                = "选择证书（{0}）"
  "CheckBasic.Menu.FileTitle"                = "选择文件（{0}）"
  "CheckBasic.Menu.Instruction"              = "↑↓ 选择 / Enter 确定 / ESC 返回"
  "CheckBasic.Menu.NoCerts"                  = "未找到证书"
  "CheckBasic.Menu.BackPrompt"               = "按 Enter 返回"

  # Test-CertificateKeyMatch.ps1 detail sections
  "VerifyMatch.Detail.CertInfo"              = "--- 证书信息 ---"
  "VerifyMatch.Detail.KeyInfo"               = "--- 私钥信息 ---"
  "VerifyMatch.Detail.CsrInfo"               = "--- CSR 信息 ---"
  "VerifyMatch.Detail.Subject"               = "Subject:"
  "VerifyMatch.Detail.Modulus"               = "Modulus:"

  # Request-LetsEncryptCertificate.ps1
  # Request-LetsEncryptCertificate.ps1
  "LE.InputDomainPrompt"                     = "请输入要签发证书的域名。"
  "LE.InputEmailPrompt"                      = "请输入 Let's Encrypt 注册用的电子邮件地址。"
  "LE.CommandNotFound"                       = "命令未找到: {0}"
  "LE.Ready"                                 = "== 准备就绪 =="
  "LE.Domain"                                = "域名: {0}"
  "LE.CleaningWorkDir"                       = "[信息] 正在删除现有工作目录: {0}"
  "LE.ReusingWorkDir"                        = "[信息] 复用现有工作目录: {0}"
  "LE.ChallengeDir"                          = "本地 challenge 文件目录:"
  "LE.ServerChallengeDir"                    = "服务器 challenge 目录（提示）:"
  "LE.ExportDir"                             = "证书导出目录:"
  "LE.DockerMountCheck"                      = "== Docker 挂载自检 =="
  "LE.DockerMountFailed"                     = "Docker 挂载自检失败: 容器内看不到 /work/auth.sh。请检查 Docker Desktop 文件共享设置。"
  "LE.StartingCertbot"                       = "== 启动 certbot（Docker） =="
  "LE.CertbotAttempt"                        = "[信息] certbot 执行 {0}/{1}"
  "LE.CertbotFailed"                         = "certbot 失败（退出码: {0}）。请查看日志: {1}"
  "LE.CaaServfailRetryDetected"              = "[警告] 检测到 CAA 的 DNS SERVFAIL（第 {0}/{1} 次）。将在 {2} 秒后重试。"
  "LE.CaaServfailRetryExhausted"             = "[警告] CAA 的 DNS SERVFAIL 持续出现，已达到最大尝试次数 {0}。"
  "LE.RateLimitError"                        = "[警告] 已达到 Let's Encrypt 速率限制"
  "LE.RateLimitRetryAfter"                   = "可重试时间: {0}"
  "LE.RateLimitHint"                         = "提示: Let's Encrypt 对同一域名集合在 168 小时（7天）内最多签发 5 个证书。`n详情: https://letsencrypt.org/docs/rate-limits/"
  "LE.RateLimitFailed"                       = "因速率限制导致证书获取失败。请等待上述可重试时间，或尝试其他域名。"
  "LE.ErrorLogTail"                          = "错误日志（末尾50行）:"
  "LE.Exporting"                             = "== 导出证书到宿主机 =="
  "LE.ExportFailedTrying"                    = "[警告] 导出到 {0} 失败，尝试回退到 {1}..."
  "LE.ExportFailed"                          = "导出失败: {0} 和 {1} 都无法写入。请检查 Docker Desktop 文件共享/安全软件拦截。"
  "LE.ExportDirCreateFailed"                 = "[警告] 导出目录创建失败: {0}。回退到: {1}"
  "LE.ExportDirFallback"                     = "[信息] 已更改导出目录: {0}"
  "LE.ExportZeroBytes"                       = "导出文件为 0 字节（{0}={1}, {2}={3}）。请检查权限/拦截。"
  "LE.ExportFilesMissing"                    = "找不到导出的文件: {0} 或 {1}"
  "LE.ExportSuccess"                         = "[成功] {0} ({1} bytes)"
  "LE.CompletedMsg"                          = "Let's Encrypt 证书获取完成。"
  "LE.PressAnyKeyToReturn"                   = "按任意键返回菜单..."

  # Request-SelfSignedCertificate.ps1
  "SS.Menu.Title"                            = "自签证书（{0} 天 / 约 {1} 年）"
  "SS.Menu.ValidityTitle"                    = "请选择证书有效期"
  "SS.Validity.90d"                          = "90 天"
  "SS.Validity.1y"                           = "1 年（365 天）"
  "SS.Validity.3y"                           = "3 年（1095 天）"
  "SS.Validity.10y"                          = "10 年（3650 天）"
  "SS.Menu.Quick"                            = "快速生成（基于 old 机构证书的 CN）"
  "SS.Menu.Custom"                           = "自定义生成（可指定Subject与输出目录）"
  "SS.Menu.QuickSelectOrg"                   = "选择机构（Quick）"
  "SS.Menu.NoOrg"                            = "在 old 目录下未找到机构文件夹。"
  "SS.Menu.NoCertInOrg"                      = "所选机构下未找到证书文件: {0}"
  "SS.Prompt.CN"                             = "CN"
  "SS.Prompt.SubjectOptional"                = "Subject（可选）"
  "SS.Prompt.SANOptional"                    = "SAN（可选）"
  "SS.Prompt.OutDirOptional"                 = "输出目录（可选）"
  "SS.InputCnPrompt"                         = "请输入 CN（例如: example.com）。"
  "SS.InputSubjectPrompt"                    = "如需自定义 Subject，请输入（留空则使用 /CN=<CN>）。"
  "SS.InputSanPrompt"                        = "请输入 SAN（可选）。留空将自动使用 DNS:CN。"
  "SS.InputOutDirPrompt"                     = "如需自定义输出目录，请输入（留空使用默认目录）。"
  "SS.OpenSslNotFound"                       = "未找到 OpenSSL。请检查指定路径或确保可直接执行 openssl 命令: {0}"
  "SS.OutExistsNoOverwrite"                  = "输出文件已存在。若要覆盖请加 -Overwrite。`n{0}"
  "SS.Starting"                              = "== 正在生成自签证书（{0} 天 / 约 {1} 年） =="
  "SS.Info.CN"                               = "CN: {0}"
  "SS.Info.Subject"                          = "Subject: {0}"
  "SS.Info.SAN"                              = "SAN: {0}"
  "SS.Info.Validity"                         = "有效期: {0} 天（约 {1} 年）"
  "SS.Info.OutDir"                           = "输出目录: {0}"
  "SS.Done.Key"                              = "[成功] 私钥: {0}"
  "SS.Done.Cert"                             = "[成功] 证书: {0}"
  "SS.Done.NotAfter"                         = "[成功] 到期时间: {0}"
  "SS.Done.Warning"                          = "[注意] 自签证书不是公共 CA 证书，请仅用于内部或测试场景。"
  "SS.Quick.StartOrg"                        = "== 开始处理机构: {0} =="
  "SS.Quick.ProcessingCert"                  = "[处理中] {0} -> CN={1}"
  "SS.Quick.CnFromCertFailed"                = "[警告] 无法从证书提取 CN: {0}"
  "SS.Quick.SkipDuplicateCn"                 = "[跳过] 检测到重复 CN: {0}"
  "SS.Quick.Completed"                       = "== 机构处理完成: {0} =="
  "SS.Quick.SuccessCount"                    = "成功数量: {0}"
  "SS.Quick.FailCount"                       = "失败数量: {0}"
  "SS.PressAnyKeyReturnOrg"                  = "按任意键返回机构列表..."

  # Repair-PemFile.ps1
  "RepairPem.ReadFailed"                     = "读取文件失败: {0}"
  "RepairPem.ZeroBytes"                      = "文件是 0 字节: {0}"
  "RepairPem.EmptyAfterBom"                  = "去除 BOM 后文件为空: {0}"
  "RepairPem.NoPemBlock"                     = "[{0}] 未找到有效的 PEM 块（BEGIN/END）。文件可能不是 PEM 格式或已损坏: {1}"
  "RepairPem.ParseFailed"                    = "[{0}] PEM 块解析失败: {1}"
  "RepairPem.TooShort"                       = "[{0}] PEM 正文过短（{1} 字符），疑似截断/损坏: {2}"
  "RepairPem.InvalidHeader"                  = "[{0}] 第一行不正确: {1}"
  "RepairPem.BackupSection"                  = "== 备份文件 =="
  "RepairPem.BackupCreated"                  = "{0} 备份: {1}"
  "RepairPem.NormalizeSection"               = "== PEM 规范化 =="
  "RepairPem.VerifySection"                  = "== 验证 =="
  "RepairPem.FileInfo"                       = "{0}: {1} bytes, blocks={2}, first='{3}', last='{4}'"
  "RepairPem.NginxParamsRequired"            = "使用 -TestNginx 时需指定 -NginxExe 和 -NginxConf。"
  "RepairPem.NginxTestSection"               = "== nginx -t =="
  "RepairPem.NginxTestFailed"                = "nginx -t 失败（退出码: {0}）"
  "RepairPem.Menu.SelectSource"              = "请选择 PEM 来源"
  "RepairPem.Menu.SelectPair"                = "请选择要从 {0} 修复的 PEM 文件对"
  "RepairPem.Menu.Manual"                    = "手动输入`n  直接输入 fullchain.pem 和 privkey.pem 路径"
  "RepairPem.Menu.FullchainPrompt"           = "fullchain PEM 路径"
  "RepairPem.Menu.PrivkeyPrompt"             = "privkey PEM 路径"
  "RepairPem.Menu.NoCandidates"              = "在以下目录下未找到 PEM 文件对: {0}"
  "RepairPem.Success"                        = "[成功] PEM 文件修复完成。"
  "RepairPem.Failed"                         = "[失败] {0}"
  "RepairPem.RestoreHint"                    = "提示: 可用刚创建的 .bak_ 时间戳文件回滚。"

  # Install-Dependencies.ps1
  "Deps.Title"                               = "SSL Toolkit 依赖工具安装"
  "Deps.AlreadyInstalled"                    = "[已安装] OpenSSL 已存在: {0}"
  "Deps.Version"                             = "版本: {0}"
  "Deps.UseForceHint"                        = "如需重新下载，请使用 -Force 参数。"
  "Deps.Downloading"                         = "[下载] 正在尝试下载便携版 OpenSSL..."
  "Deps.TryingSource"                        = "[尝试] 下载源: {0}"
  "Deps.DownloadTooSmall"                    = "[警告] 下载的文件太小，可能无效。"
  "Deps.Extracting"                          = "[解压] 正在解压..."
  "Deps.OpenSslNotFoundInArchive"            = "[警告] 压缩包中未找到 openssl.exe。"
  "Deps.ExtractedButNotWorking"              = "[警告] 解压完成但 OpenSSL 无法正常运行。"
  "Deps.DownloadFailed"                      = "[失败] 下载失败: {0}"
  "Deps.InstallSuccess"                      = "[成功] OpenSSL 安装完成！"
  "Deps.InstalledTo"                         = "安装路径: {0}"
  "Deps.AutoFailed"                          = "[失败] 自动下载未成功。请按照以下步骤手动安装:"
  "Deps.ManualGuide"                         = "手动安装指南:"
  "Deps.ManualStep1"                         = "  1. 从 https://slproweb.com/products/Win32OpenSSL.html 下载 Win64 OpenSSL"
  "Deps.ManualStep2"                         = "  2. 将 openssl.exe 及相关 DLL 复制到: {0}"
  "Deps.ManualStep3"                         = "  3. 或者安装 Git for Windows (自带 OpenSSL)"
  "Deps.ManualAlt1"                          = "替代方案: winget install ShiningLight.OpenSSL"
  "Deps.ManualAlt2"                          = "替代方案: 安装 Git for Windows (https://git-scm.com/)"
}
