@{
  # Common
  "Common.Yes" = "Yes"
  "Common.No" = "No"
  "Common.Success" = "Success"
  "Common.Failed" = "Failed"
  "Common.Skip" = "Skip"
  "Common.Info" = "Info"
  "Common.Warn" = "Warning"
  "Common.FileNotFound" = "{0} not found: {1}"
  "Common.OpenSslCmdFailed" = "OpenSSL command failed: {0}`n{1}"
  "Common.Exists" = "exists"
  "Common.NotExists" = "missing"
  "Common.I18nModuleNotFound" = "i18n module not found: {0}"
  "Common.DirNotFound" = "{0} not found: {1}"

  # Common labels
  "Label.Old" = "old"
  "Label.New" = "new"
  "Label.Cert" = "Certificate"
  "Label.Csr" = "CSR"
  "Label.Key" = "Private key"

  # Get-CertificateInfo.ps1
  "CheckBasic.Header" = "========== {0} =========="
  "CheckBasic.Dir" = "[DIR] {0}"
  "CheckBasic.PassFilePresent" = "pass:{0}"
  "CheckBasic.PassFileMissing" = "pass:{0} missing"
  "CheckBasic.PassEnvPresent" = "PASS_FILE:present"
  "CheckBasic.PassEnvMissingFile" = "PASS_FILE:not found"
  "CheckBasic.None" = "(none)"
  "CheckBasic.NotFound" = "not found"
  "CheckBasic.Cert.NotMerged" = "not merged"
  "CheckBasic.Cert.NeedMerge" = "merge needed"
  "CheckBasic.Cert.Candidate" = "candidate:{0}"
  "CheckBasic.Cert.Issuer" = "issuer:{0}"
  "CheckBasic.Cert.HasChain" = "chain included"
  "CheckBasic.Cert.UsableGuess" = "usable (guess)"
  "CheckBasic.Cert.Unk" = "unknown"
  "CheckBasic.Cert.FormatUnknown" = "unknown"
  "CheckBasic.Cert.Expiry" = "expires:{0}"
  "CheckBasic.Cert.ChainFile" = "Chain file"
  "CheckBasic.Cert.ChainBlocks" = "Chain blocks"
  "CheckBasic.Cert.ChainFormat" = "Chain format"
  "CheckBasic.Cert.ChainFileBlocks" = "chain:{0}"
  "CheckBasic.Cert.ChainFileFound" = "chain:found"
  "CheckBasic.ChainFileIgnored" = "[INFO] -ChainFile is only valid with -Path; ignored."
  "CheckBasic.Pretty.CertTitle" = "Certificates (Pretty Table)"
  "CheckBasic.Pretty.CsrTitle" = "CSRs (Pretty Table)"
  "CheckBasic.Pretty.KeyTitle" = "Keys (Pretty Table)"
  "CheckBasic.Pretty.Path" = "Path"
  "CheckBasic.Pretty.File" = "File"
  "CheckBasic.Pretty.Expiry" = "Expiry"
  "CheckBasic.Pretty.Chain" = "Chain"
  "CheckBasic.Pretty.ChainFile" = "Chain File"
  "CheckBasic.Pretty.Blocks" = "Blocks"
  "CheckBasic.Pretty.ChainBlocks" = "Chain Blocks"
  "CheckBasic.Pretty.Issuer" = "Issuer"
  "CheckBasic.Pretty.Format" = "Format"
  "CheckBasic.Pretty.Subject" = "Subject"
  "CheckBasic.Pretty.Encrypted" = "Encrypted"
  "CheckBasic.Pretty.AutoMode" = "Auto Mode"
  "CheckBasic.Pretty.Decrypt" = "Decrypt"
  "CheckBasic.Key.Encrypted" = "encrypted"
  "CheckBasic.Key.Plain" = "plain"
  "CheckBasic.Key.DecOk" = "decrypt:ok"
  "CheckBasic.Key.DecFail" = "decrypt:fail"
  "CheckBasic.Key.DecSkip" = "decrypt:{0}"
  "CheckBasic.Key.AutoOkNoPass" = "unattended OK (no pass needed)"
  "CheckBasic.Key.AutoOkNeedPass" = "unattended OK (decrypt needed / no prompt)"
  "CheckBasic.Key.AutoNgNeedPass" = "unattended NO (no pass and no prompt)"
  "CheckBasic.Key.SkipNoPass" = "skip(no pass)"
  "CheckBasic.Key.SkipNoPassLong" = "skip (no pass)"

  # Detail mode labels (Get-CertificateInfo.ps1)
  "CheckBasic.Detail.File" = "[FILE] {0}"
  "CheckBasic.Detail.Key" = "[KEY]"
  "CheckBasic.Detail.Key.Encrypted" = "[KEY] Encrypted: {0}"
  "CheckBasic.Detail.Key.PassFile" = "[KEY] Pass file({0}): {1}"
  "CheckBasic.Detail.Key.EnvPassSet" = "[KEY] Env PASS_FILE: set ({0} / {1})"
  "CheckBasic.Detail.Key.EnvPassUnset" = "[KEY] Env PASS_FILE: unset"
  "CheckBasic.Detail.Key.Auto" = "[KEY] Unattended: {0}"
  "CheckBasic.Detail.Key.DecCheck" = "[KEY] Decrypt check: {0}"
  "CheckBasic.Detail.Key.CannotReadNeedPass" = "[WARN] Cannot read encrypted key (prepare {0} or -PassFile / env PASS_FILE)"
  "CheckBasic.Detail.Key.CannotRead" = "[WARN] Cannot read key"
  "CheckBasic.Detail.UnsupportedExt" = "Unsupported extension: {0}"
  "CheckBasic.Detail.Cert.HasPrivateKey" = "[WARN] Certificate file contains what appears to be a private key block"
  "CheckBasic.Detail.Cert.NoChainHint" = "[CERT] Note: Intermediate certificate is not included. Use Merge-CertificateChain.ps1 if needed."

  # Merge-CertificateChain.ps1
  "MergeCert.TitleSingle" = "========== Certificate chain merge tool =========="
  "MergeCert.TitleBatch" = "========== Certificate chain merge tool (batch) =========="
  "MergeCert.Step1" = "[1] Checking input files..."
  "MergeCert.Step2" = "[2] Normalizing line endings and merging..."
  "MergeCert.ClientCert" = "[OK] Client certificate: {0}"
  "MergeCert.IntermediateCert" = "[OK] Intermediate (CA) certificate: {0}"
  "MergeCert.AlreadyHasChain" = "[INFO] Certificate may already include a chain (CERT blocks={0}); not appending intermediate."
  "MergeCert.SameAsExistingSkip" = "[INFO] Output content is identical; skipping: {0}"
  "MergeCert.Done" = "[OK] Certificate chain created"
  "MergeCert.OutFile" = "Output file: {0}"
  "MergeCert.ChainOutFile" = "Chain file: {0}"
  "MergeCert.ChainCert" = "[OK] Chain certificate: {0}"
  "MergeCert.RootCerts" = "[OK] Root certificate(s): {0}"
  "MergeCert.ChainFromClient" = "[INFO] Using chain from client certificate (remaining blocks)."
  "MergeCert.NoChainData" = "No chain data available for chainfile output."
  "MergeCert.NoCertBlock" = "No certificate block found in client certificate."
  "MergeCert.AutoFetchStart" = "[INFO] Auto-fetching issuer certificate from AIA..."
  "MergeCert.AutoFetchUrl" = "[INFO] AIA URL: {0}"
  "MergeCert.AutoFetchSaved" = "[OK] Downloaded: {0}"
  "MergeCert.AutoFetchFailed" = "[WARN] Failed to download from AIA URL: {0}"
  "MergeCert.AutoFetchNoAia" = "[WARN] No AIA CA Issuers URL found in certificate: {0}"
  "MergeCert.AutoFetchNeedOpenSsl" = "[WARN] OpenSSL not available; auto-fetch disabled."
  "MergeCert.CrossRootHint" = "[INFO] Cross root certificate in use ({0}); usually OK for browser trust chains."
  "MergeCert.RootDir" = "[DIR] RootDir: {0}"
  "MergeCert.OutDir" = "[DIR] OutDir : {0}"
  "MergeCert.NoTargets" = "[INFO] No target certificates found (.cer/.crt/.pem)"
  "MergeCert.NoIntermediateCandidates" = "Intermediate cert not specified and no candidates found in the root directory. Specify -IntermediateCert."
  "MergeCert.MultiIntermediateMatched" = "Multiple intermediate candidates matched (issuer/subject). To avoid wrong merge, specify -IntermediateCert.`n{0}"
  "MergeCert.NoIntermediateMatched" = "Auto-selection failed (no candidate subject matches issuer). Aborting to avoid wrong merge.`nissuer={0}`nCandidates:`n{1}"
  "MergeCert.OneCandidateButNoVerify" = "One intermediate candidate exists but issuer/subject verification is not possible; refusing auto-selection. Specify -IntermediateCert: {0}"
  "MergeCert.MultiCandidatesNeedSpecify" = "Intermediate cert not specified and multiple candidates exist. To avoid wrong merge, specify -IntermediateCert.`n{0}"
  "MergeCert.RootDirNotFound" = "RootDir not found: {0}"

  # Convert-KeyToPlaintext.ps1
  "DecryptKey.PathNotFound" = "Path not found: {0}"
  "DecryptKey.KeyHeader" = "[KEY] {0}"
  "DecryptKey.EncryptedLine" = "[INFO] Encrypted: {0}"
  "DecryptKey.SkipPlain" = "[SKIP] Already a plain key (no decrypt needed)"
  "DecryptKey.PassFilesLine" = "[PASS] Pass file({0}): {1}"
  "DecryptKey.PassEnvLine" = "[PASS] Env PASS_FILE: set ({0} / {1})"
  "DecryptKey.PassEnvUnset" = "[PASS] Env PASS_FILE: unset"
  "DecryptKey.NoPassphrase" = "Passphrase not found (no interactive prompt). Prepare {0} or PASS_FILE."
  "DecryptKey.InPlaceNeedOverwrite" = "InPlace is dangerous; you must specify -Overwrite (a backup will be created)."
  "DecryptKey.BackupFailed" = "Failed to create backup: {0}"
  "DecryptKey.BackupLine" = "[BAK] Backed up original encrypted key: {0}"
  "DecryptKey.InPlaceLine" = "[INFO] -InPlace: output filename will not change: {0}"
  "DecryptKey.OutExistsNoOverwrite" = "Output file already exists (overwrite blocked): {0}`nSpecify -Overwrite to overwrite."
  "DecryptKey.DecryptFailed" = "Decrypt failed (passphrase mismatch is likely)."
  "DecryptKey.StillEncrypted" = "Decrypted output is still encrypted (unexpected). Check: {0}"
  "DecryptKey.Done" = "[OK] Decrypted key: {0}"
  "DecryptKey.NoKeys" = "[INFO] No target .key found"
  "DecryptKey.NgPath" = "[NG] {0}"
  "DecryptKey.NgMsg" = "[NG] {0}"

  # New-CertificateSigningRequest.ps1
  "MakeCsr.CnRequired" = "CN is required."
  "MakeCsr.SubjectMissing" = "Subject is missing. Provide -Subject, or specify all of -C/-ST/-L/-O."
  "MakeCsr.OutExistsNoOverwrite" = "Output already has existing files (overwrite blocked): {0}`nSpecify -Overwrite to regenerate."
  "MakeCsr.PassFileUnreadable" = "Cannot read passphrase from PassFile: {0}"
  "MakeCsr.DoneKey" = "[OK] Key: {0}"
  "MakeCsr.DoneCsr" = "[OK] CSR: {0}"
  "MakeCsr.PreviewTitle" = "[INFO] CSR preview (Subject / SAN)"

  # Export-CertificateModulus.ps1
  "ShowModulus.Title" = "========== Certificate / key modulus list =========="
  "ShowModulus.CreatedAt" = "Created at: {0}"
  "ShowModulus.SectionCert" = "Certificates (.cer, .crt, .pem)"
  "ShowModulus.SectionKey" = "Private keys (.key)"
  "ShowModulus.InvalidCert" = "[Invalid certificate or multiple certificates are contained in the file]"
  "ShowModulus.SkipEncryptedKey" = "[Skipping encrypted key: prepare {0} or specify -PassFile / env PASS_FILE]"
  "ShowModulus.KeyReadError" = "[Failed to read key or invalid format]"
  "ShowModulus.SummaryTitle" = "Summary"
  "ShowModulus.SummaryCertCount" = "Certificates processed: {0}"
  "ShowModulus.SummaryKeyCount" = "Keys processed: {0}"
  "ShowModulus.Advice1" = "Compare modulus values to verify matches."
  "ShowModulus.Advice2" = "If cert and key modulus are identical, they are a pair."
  "ShowModulus.ConsoleTitle" = "[OK] Summary"
  "ShowModulus.SavedTo" = "Saved to: {0}"

  # Test-CertificateKeyMatch.ps1
  "VerifyMatch.ReportTitle" = "Certificate / key / CSR match report"
  "VerifyMatch.CreatedAt" = "Created at: {0}"
  "VerifyMatch.Separator" = "=============================================="
  "VerifyMatch.ConsoleTitle" = "========== Certificate / key / CSR match =========="
  "VerifyMatch.Scanning" = "Scanning folders (mode={0})..."
  "VerifyMatch.FolderMissing" = "[INFO] Folder not found: {0}"
  "VerifyMatch.Checking" = "[{0}] Checking: {1}\\{2}\\{3}"
  "VerifyMatch.ReportHeader" = "[{0}] root: {1}  org: {2}  server: {3}"
  "VerifyMatch.DetectedFiles" = "Detected files:"
  "VerifyMatch.DetectedCert" = "  [CERT] {0}"
  "VerifyMatch.DetectedKey" = "  [KEY ] {0}"
  "VerifyMatch.DetectedCsr" = "  [CSR ] {0}"
  "VerifyMatch.ConsoleCertMissing" = "  Cert: missing"
  "VerifyMatch.ConsoleCertFound" = "  Cert: found"
  "VerifyMatch.ConsoleKeyMissing" = "  Key : missing"
  "VerifyMatch.ConsoleKeyFound" = "  Key : found"
  "VerifyMatch.ConsoleCsrMissing" = "  CSR : missing"
  "VerifyMatch.ConsoleCsrFound" = "  CSR : found"
  "VerifyMatch.Judgement" = "--- Judgement ---"
  "VerifyMatch.NoFiles" = "[ERROR] No target files"
  "VerifyMatch.MatchCertKey" = "[OK] Cert vs Key modulus match"
  "VerifyMatch.MismatchCertKey" = "[NG] Cert vs Key modulus mismatch"
  "VerifyMatch.MatchCertKeyDetail" = "[OK] Cert({0}) vs Key({1}) modulus match"
  "VerifyMatch.MismatchCertKeyDetail" = "[NG] Cert({0}) vs Key({1}) modulus mismatch"
  "VerifyMatch.MatchCertCsr" = "[OK] Cert vs CSR modulus match"
  "VerifyMatch.MismatchCertCsr" = "[NG] Cert vs CSR modulus mismatch"
  "VerifyMatch.MatchCertCsrDetail" = "[OK] Cert({0}) vs CSR({1}) modulus match"
  "VerifyMatch.MismatchCertCsrDetail" = "[NG] Cert({0}) vs CSR({1}) modulus mismatch"
  "VerifyMatch.MatchKeyCsr" = "[OK] Key vs CSR modulus match"
  "VerifyMatch.MismatchKeyCsr" = "[NG] Key vs CSR modulus mismatch"
  "VerifyMatch.MatchKeyCsrDetail" = "[OK] Key({0}) vs CSR({1}) modulus match"
  "VerifyMatch.MismatchKeyCsrDetail" = "[NG] Key({0}) vs CSR({1}) modulus mismatch"
  "VerifyMatch.ConsoleMatchCertKey" = "  Cert <-> Key: match"
  "VerifyMatch.ConsoleMismatchCertKey" = "  Cert <-> Key: mismatch"
  "VerifyMatch.ConsoleMatchCertCsr" = "  Cert <-> CSR: match"
  "VerifyMatch.ConsoleMismatchCertCsr" = "  Cert <-> CSR: mismatch"
  "VerifyMatch.ConsoleMatchKeyCsr" = "  Key <-> CSR: match"
  "VerifyMatch.ConsoleMismatchKeyCsr" = "  Key <-> CSR: mismatch"
  "VerifyMatch.ConsoleInsufficient" = "  [WARN] Missing files required for comparison"
  "VerifyMatch.Insufficient" = "[WARN] Missing files required for comparison"
  "VerifyMatch.ConsoleFinalOk" = "  Final: MATCH (valid set)"
  "VerifyMatch.ConsoleFinalNg" = "  Final: MISMATCH (invalid set)"
  "VerifyMatch.FinalOk" = "[RESULT] MATCH (valid set)"
  "VerifyMatch.FinalNg" = "[RESULT] MISMATCH (invalid set)"
  "VerifyMatch.SummaryTitle" = "Summary"
  "VerifyMatch.SummaryTotal" = "Checked sets: {0}"
  "VerifyMatch.SummaryOk" = "Match (valid): {0}"
  "VerifyMatch.SummaryNg" = "Mismatch (invalid): {0}"
  "VerifyMatch.SavedTo" = "Saved to: {0}"
  "VerifyMatch.ReportSavedTo" = "Report saved to: {0}"

  # New-CertificateSigningRequestFromOld.ps1
  "Renew.MenuTitle" = "Multiple organizations found. Select organizations to process."
  "Renew.MenuHint" = "(e.g., 1 or 1,3 / all / q)"
  "Renew.MenuPrompt" = "Select"
  "Renew.NoInteractive" = "Interactive input is not available. Specify -Org or -All."
  "Renew.Cancelled" = "Cancelled."
  "Renew.InvalidInput" = "[WARN] Invalid input. Please try again."
  "Renew.CnMissingInSubject" = "Cannot get CN from Subject"
  "Renew.New.NotGenerated" = "new=not generated"
  "Renew.New.NotGeneratedRoot" = "new=not generated (0/{0})"
  "Renew.New.GeneratedRoot" = "new=generated ({0}/{1})"
  "Renew.New.GeneratedNoLatest" = "new=generated (sets~{0}, csr={1}, key={2})"
  "Renew.New.GeneratedWithLatest" = "new=generated (sets~{0}, csr={1}, key={2}, latest={3})"
  "Renew.OldDirMissing" = "OldDir does not exist: {0}"
  "Renew.RootNoCerts" = "No certificates directly under old; cannot select -Org (root)."
  "Renew.OrgFolderMissing" = "Specified org folder does not exist: {0}"
  "Renew.NoOrgFound" = "No org folders/certificates found under old: {0}"
  "Renew.MultiOrgNeedSpecify" = "Multiple organizations found. Specify -Org or -All."
  "Renew.MultiOverwriteForbidden" = "Dangerous: -Overwrite cannot be used for multiple orgs. Limit to one org with -Org."
  "Renew.MultiOverwriteWarn" = "[WARN] -Overwrite with multiple orgs will backup and regenerate server.key/server.csr."
  "Renew.MultiOverwriteConfirmPrompt" = "Type YES to continue"
  "Renew.CnNotFound" = "Cannot get CN: cert={0} subject=[{1}] csr=[{2}]"
  "Renew.BackupKeyFail" = "Cannot backup existing server.key: {0}"
  "Renew.BackupCsrFail" = "Cannot backup existing server.csr: {0}"
  "Renew.OutExistsNoOverwrite" = "Output already exists (overwrite blocked): {0}`nSpecify -Overwrite to regenerate."
  "Renew.DoneTitle" = "Generated:"
  "Renew.ShowInfo.OpenSsl" = "OpenSSL: {0}"
  "Renew.ShowInfo.OldDir" = "OldDir : {0}"
  "Renew.ShowInfo.NewDir" = "NewDir : {0}"
  "Renew.ShowInfo.Version" = "OpenSSL version: {0}"
  "Renew.Table.Org" = "Organization"
  "Renew.Table.Cn" = "CN"
  "Renew.Table.RsaBits" = "Key Length"
  "Renew.Table.San" = "SAN"
  "Renew.Table.OutDir" = "Output"

  # Common error messages
  "Common.FolderNotFound" = "[INFO] Folder not found: {0}: {1}"
  "Common.NoTargetFiles" = "[INFO] No target files found"
  "Common.NoCertFiles" = "[INFO] No certificate files (.cer/.crt/.pem) found (chain check will be skipped)"
  "Common.ErrorNg" = "[NG] {0}"

  # Test-CertificateKeyMatch.ps1 detail sections
  "VerifyMatch.Detail.CertInfo" = "--- Certificate Info ---"
  "VerifyMatch.Detail.KeyInfo" = "--- Private Key Info ---"
  "VerifyMatch.Detail.CsrInfo" = "--- CSR Info ---"
  "VerifyMatch.Detail.Subject" = "Subject:"
  "VerifyMatch.Detail.Modulus" = "Modulus:"

  # Request-LetsEncryptCertificate.ps1
  "LE.CommandNotFound" = "Command not found: {0}"
  "LE.Ready" = "== Ready =="
  "LE.Domain" = "Domain: {0}"
  "LE.CleaningWorkDir" = "[INFO] Cleaning existing work directory: {0}"
  "LE.ReusingWorkDir" = "[INFO] Reusing existing work directory: {0}"
  "LE.ChallengeDir" = "Local challenge file directory:"
  "LE.ServerChallengeDir" = "Server challenge directory (hint):"
  "LE.ExportDir" = "Certificate export directory:"
  "LE.DockerMountCheck" = "== Docker mount self-check =="
  "LE.DockerMountFailed" = "Docker mount self-check failed: /work/auth.sh not visible inside container. Check Docker Desktop file sharing settings."
  "LE.StartingCertbot" = "== Starting certbot (Docker) =="
  "LE.CertbotFailed" = "certbot failed (exit code: {0}). Check logs: {1}"
  "LE.RateLimitError" = "[WARN] Let's Encrypt rate limit reached"
  "LE.RateLimitRetryAfter" = "Retry after: {0}"
  "LE.RateLimitHint" = "Hint: Let's Encrypt has a limit of 5 certificates per exact set of identifiers per 168 hours (7 days).`nDetails: https://letsencrypt.org/docs/rate-limits/"
  "LE.RateLimitFailed" = "Certificate request failed due to rate limit. Wait until the retry time above, or try a different domain."
  "LE.ErrorLogTail" = "Error log (last 50 lines):"
  "LE.Exporting" = "== Exporting certificate to host =="
  "LE.ExportFailedTrying" = "[WARN] Export to {0} failed, trying fallback {1}..."
  "LE.ExportFailed" = "Export failed: cannot write to {0} or {1}. Check Docker Desktop file sharing/security software."
  "LE.ExportDirCreateFailed" = "[WARN] Failed to create export directory: {0}. Fallback to: {1}"
  "LE.ExportDirFallback" = "[INFO] Changed export directory to: {0}"
  "LE.ExportZeroBytes" = "Exported file is 0 bytes ({0}={1}, {2}={3}). Check permissions/blocking."
  "LE.ExportFilesMissing" = "Exported files not found: {0} or {1}"
  "LE.ExportSuccess" = "[OK] {0} ({1} bytes)"

  # Repair-PemFile.ps1
  "RepairPem.ReadFailed" = "Failed to read file: {0}"
  "RepairPem.ZeroBytes" = "File is 0 bytes: {0}"
  "RepairPem.EmptyAfterBom" = "File is empty after BOM removal: {0}"
  "RepairPem.NoPemBlock" = "[{0}] No valid PEM block (BEGIN/END) found. File may not be PEM format or is corrupted: {1}"
  "RepairPem.ParseFailed" = "[{0}] Failed to parse PEM block: {1}"
  "RepairPem.TooShort" = "[{0}] PEM body too short ({1} chars), possibly truncated/corrupted: {2}"
  "RepairPem.InvalidHeader" = "[{0}] First line is invalid: {1}"
  "RepairPem.BackupSection" = "== Creating Backup =="
  "RepairPem.BackupCreated" = "{0} backup: {1}"
  "RepairPem.NormalizeSection" = "== Normalizing PEM =="
  "RepairPem.VerifySection" = "== Verification =="
  "RepairPem.FileInfo" = "{0}: {1} bytes, blocks={2}, first='{3}', last='{4}'"
  "RepairPem.NginxParamsRequired" = "-NginxExe and -NginxConf are required when using -TestNginx."
  "RepairPem.NginxTestSection" = "== nginx -t =="
  "RepairPem.NginxTestFailed" = "nginx -t failed (exit code: {0})"
  "RepairPem.Success" = "[OK] PEM file repair completed."
  "RepairPem.Failed" = "[FAILED] {0}"
  "RepairPem.RestoreHint" = "Hint: You can restore using the .bak_ timestamped file just created."
}
