@{
  # Language metadata
  "Language.DisplayName"                     = "日本語"
  "Language.VersionCheckError"               = "[エラー] PowerShell 7.x 以上が必要です。"
  "Language.VersionCheckCurrent"             = "現在のバージョン"

  # Common
  "Common.Yes"                               = "はい"
  "Common.No"                                = "いいえ"
  "Common.Success"                           = "成功"
  "Common.Failed"                            = "失敗"
  "Common.Skip"                              = "スキップ"
  "Common.Info"                              = "情報"
  "Common.Warn"                              = "警告"
  "Common.MenuCancel"                        = "キャンセル"
  "Common.MenuAll"                           = "すべて"
  "Common.MenuQuit"                          = "終了"
  "Common.MenuBack"                          = "戻る"
  "Common.Cancelled"                         = "キャンセルされました"
  "Common.Welcome"                           = "SSL 証明書管理ツール"
  "Common.PressAnyKey"                       = "何かキーを押すと続行します..."
  "Toolkit.ExitConfirmation"                 = "終了します。何かキーを押すと閉じます..."
  "Common.Prompt.Domain"                     = "ドメイン"
  "Common.Prompt.Email"                      = "メールアドレス"

  "Toolkit.Banner.Title"                     = "SSL 証明書管理ツール"
  "Toolkit.Banner.Version"                   = "Ver {0}  https://github.com/sunshaoxuan"
  "Toolkit.Exit.VersionLine"                 = "バージョン: {0}"
  "Toolkit.Exit.UpdatedLine"                 = "最終更新: {0}"
  "Toolkit.Exit.Copyright"                   = "Copyright (c) sunshaoxuan"
  "Toolkit.Exit.Thanks"                      = "ご利用ありがとうございました！"

  # Toolkit menu
  "Toolkit.Menu.Title"                       = "ツールを選択 (↑↓で選択, Enterで実行, ESCで終了)"
  "Toolkit.Menu.Exit"                        = "[ 終了 ]"
  "Toolkit.Menu.Back"                        = "[ 戻る ]"
  "Toolkit.Menu.Language"                    = "言語"
  "Toolkit.Menu.SelectLanguage"              = "表示言語を選択"
  "Toolkit.Menu.SubMenuSelect"               = "{0} - 種類を選択"
  "Toolkit.Menu.Starting"                    = "起動中: {0}"
  "Toolkit.Menu.PressAnyKey"                 = "任意のキーを押してメニューに戻る..."
  "Toolkit.Menu.AutoRename"                  = "起動時自動処理: 組織フォルダのリネーム確認を実行します..."
  "Toolkit.Menu.AutoRenameFailed"            = "自動リネーム確認に失敗したためスキップしました: {0}"
  "Toolkit.Menu.ScriptNotFound"              = "スクリプトが見つかりません: {0}"

  # Tool descriptions
  "Toolkit.Tool.CertInfo"                    = "証明書情報を確認"
  "Toolkit.Tool.CsrFromOld"                  = "既存証明書からCSR更新"
  "Toolkit.Tool.NewCsr"                      = "新規CSR作成"
  "Toolkit.Tool.MergeChain"                  = "証明書チェーン結合"
  "Toolkit.Tool.ConvertKey"                  = "秘密鍵を平文に変換"
  "Toolkit.Tool.ExportModulus"               = "証明書モジュラス出力"
  "Toolkit.Tool.RepairPem"                   = "PEMファイル修復"
  "Toolkit.Tool.ServerList"                  = "証明書更新TSVを出力"
  "Toolkit.Tool.SyncMerged"                  = "new→output/merged同期 (key,csr,tsv)"
  "Toolkit.Tool.SelfSigned"                  = "自己署名証明書"
  "Toolkit.SubTool.SelfSigned"               = "自己署名証明書を作成"
  "Toolkit.SubTool.SelfSigned10Y"            = "10年自己署名証明書を作成"
  "Toolkit.SubTool.LetsEncrypt"              = "Let's Encrypt 証明書を取得"
  "Common.FileNotFound"                      = "{0} が見つかりません: {1}"
  "Common.OpenSslCmdFailed"                  = "OpenSSL コマンド失敗: {0}`n{1}"
  "Common.Exists"                            = "存在"
  "Common.NotExists"                         = "未存在"
  "Common.I18nModuleNotFound"                = "i18n モジュールが見つかりません: {0}"
  "Common.DirNotFound"                       = "{0} が見つかりません: {1}"

  # Common labels
  "Label.Old"                                = "旧"
  "Label.New"                                = "新"
  "Label.Merged"                             = "結合済"
  "Label.SelfSigned"                         = "自己署名"
  "Label.Cert"                               = "証明書"
  "Label.Csr"                                = "申請(CSR)"
  "Label.Key"                                = "秘密鍵"
  "Label.File"                               = "ファイル"
  "Label.FileType"                           = "種別"
  "Label.Format"                             = "形式"
  "Label.Blocks"                             = "証明書ブロック数"
  "Label.HasChain"                           = "中間証明書同梱"
  "Label.FinalUse"                           = "最終利用"
  "Label.ExtChainCand"                       = "外部中間証明書（候補）"
  "Label.Encrypted"                          = "暗号化"
  "Label.PassFile"                           = "パスワードファイル"
  "Label.AutoMode"                           = "無人運用"
  "Label.DecryptCheck"                       = "復号チェック"
  "Label.OpenSslDetails"                     = "OpenSSL 詳細情報"
  "Label.ChainBlockServer"                   = "サーバ証明書"
  "Label.ChainBlockIntermediate"             = "中間CA証明書"
  "Label.ChainBlockRoot"                     = "ルート/交差ルート証明書"
  "Label.Subject"                            = "Subject"
  "Label.Issuer"                             = "Issuer"
  "Label.NotBefore"                          = "有効期間(開始)"
  "Label.NotAfter"                           = "有効期間(終了)"
  "Label.TimeZone"                           = "タイムゾーン"
  "Label.GmtOriginal"                        = "GMT原文"

  # Get-CertificateInfo.ps1
  "CheckBasic.Header"                        = "========== {0} =========="
  "CheckBasic.Dir"                           = "[DIR] {0}"
  "CheckBasic.PassFilePresent"               = "パスワード:{0}"
  "CheckBasic.PassFileMissing"               = "パスワード:{0}なし"
  "CheckBasic.PassEnvPresent"                = "PASS_FILE:あり"
  "CheckBasic.PassEnvMissingFile"            = "PASS_FILE:未存在"
  "CheckBasic.None"                          = "(なし)"
  "CheckBasic.NotFound"                      = "未検出"
  "CheckBasic.Cert.NotMerged"                = "未結合"
  "CheckBasic.Cert.NeedMerge"                = "要結合"
  "CheckBasic.Cert.Candidate"                = "候補:{0}"
  "CheckBasic.Cert.Issuer"                   = "発行機関:{0}"
  "CheckBasic.Cert.HasChain"                 = "中間同梱"
  "CheckBasic.Cert.UsableGuess"              = "利用可(推定)"
  "CheckBasic.Cert.Unk"                      = "不明"
  "CheckBasic.Cert.FormatUnknown"            = "不明"
  "CheckBasic.Cert.Expiry"                   = "期限:{0}"
  "CheckBasic.Cert.ChainFile"                = "チェーンファイル"
  "CheckBasic.Cert.ChainBlocks"              = "チェーンブロック数"
  "CheckBasic.Cert.ChainFormat"              = "チェーン形式"
  "CheckBasic.Cert.ChainFileBlocks"          = "チェーン:{0}"
  "CheckBasic.Cert.ChainFileFound"           = "チェーン:あり"
  "CheckBasic.Cert.SAN"                      = "SAN"
  "CheckBasic.ChainFileIgnored"              = "[情報] -ChainFile は -Path 指定時のみ有効です。"
  "CheckBasic.Pretty.CertTitle"              = "証明書"
  "CheckBasic.Pretty.CsrTitle"               = "CSR"
  "CheckBasic.Pretty.KeyTitle"               = "秘密鍵"
  "CheckBasic.Pretty.Path"                   = "パス"
  "CheckBasic.Pretty.File"                   = "ファイル"
  "CheckBasic.Pretty.Expiry"                 = "期限"
  "CheckBasic.Pretty.Chain"                  = "チェーン"
  "CheckBasic.Pretty.ChainFile"              = "チェーンファイル"
  "CheckBasic.Pretty.Blocks"                 = "ブロック数"
  "CheckBasic.Pretty.ChainBlocks"            = "チェーン数"
  "CheckBasic.Pretty.Issuer"                 = "発行機関"
  "CheckBasic.Pretty.Format"                 = "形式"
  "CheckBasic.Pretty.Subject"                = "サブジェクト"
  "CheckBasic.Pretty.SAN"                    = "SAN"
  "CheckBasic.Pretty.Encrypted"              = "暗号化"
  "CheckBasic.Pretty.AutoMode"               = "無人運用"
  "CheckBasic.Pretty.Decrypt"                = "復号"
  "CheckBasic.Key.Encrypted"                 = "暗号化"
  "CheckBasic.Key.Plain"                     = "平文"
  "CheckBasic.Key.DecOk"                     = "復号:成功"
  "CheckBasic.Key.DecFail"                   = "復号:失敗"
  "CheckBasic.Key.DecSkip"                   = "復号:{0}"
  "CheckBasic.Key.AutoOkNoPass"              = "可能（パスワード不要）"
  "CheckBasic.Key.AutoOkNeedPass"            = "可能（復号が必要 / 対話なし）"
  "CheckBasic.Key.AutoNgNeedPass"            = "不可（パスワードがないため対話不可）"
  "CheckBasic.Key.SkipNoPass"                = "スキップ(パスワードなし)"
  "CheckBasic.Key.SkipNoPassLong"            = "スキップ（パスワードなし）"

  # Detail mode labels (Get-CertificateInfo.ps1)
  "CheckBasic.Detail.File"                   = "[FILE] {0}"
  "CheckBasic.Detail.Key"                    = "[KEY]"
  "CheckBasic.Detail.Key.Encrypted"          = "[KEY] 暗号化: {0}"
  "CheckBasic.Detail.Key.PassFile"           = "[KEY] パスワードファイル({0}): {1}"
  "CheckBasic.Detail.Key.EnvPassSet"         = "[KEY] 環境変数 PASS_FILE: 設定あり（{0} / {1}）"
  "CheckBasic.Detail.Key.EnvPassUnset"       = "[KEY] 環境変数 PASS_FILE: 未設定"
  "CheckBasic.Detail.Key.Auto"               = "[KEY] 無人運用: {0}"
  "CheckBasic.Detail.Key.DecCheck"           = "[KEY] 復号チェック: {0}"
  "CheckBasic.Detail.Subject"                = "サブジェクト:"
  "CheckBasic.Detail.SAN"                    = "SAN:"
  "CheckBasic.Detail.Key.CannotReadNeedPass" = "[警告] 暗号化された秘密鍵のため読み取れません（{0} もしくは -PassFile / 環境変数 PASS_FILE を用意してください）"
  "CheckBasic.Detail.Key.CannotRead"         = "[警告] 秘密鍵を読み取れません"
  "CheckBasic.Detail.UnsupportedExt"         = "未対応の拡張子: {0}"
  "CheckBasic.Detail.Cert.HasPrivateKey"     = "秘密鍵同梱"

  # Merge-CertificateChain.ps1
  "MergeCert.TitleSingle"                    = "証明書チェーン結合ツール"
  "MergeCert.TitleBatch"                     = "証明書チェーン結合ツール（一括）"
  "MergeCert.Step1"                          = "入力ファイルの確認"
  "MergeCert.Step2"                          = "改行コード統一とチェーン結合"
  "MergeCert.ClientCert"                     = "クライアント証明書"
  "MergeCert.IntermediateCert"               = "中間証明書(CA)"
  "MergeCert.AlreadyHasChain"                = "証明書は既にチェーンを含んでいる可能性があります（CERTブロック数={0}）。中間証明書の追加をスキップします。"
  "MergeCert.SameAsExistingSkip"             = "出力ファイルの内容が既存と同一のためスキップしました: {0}"
  "MergeCert.Done"                           = "チェーン生成完了"
  "MergeCert.OutFile"                        = "出力ファイル: {0}"
  "MergeCert.ChainOutFile"                   = "チェーンファイル: {0}"
  "MergeCert.ChainCert"                      = "チェーン証明書"
  "MergeCert.RootCerts"                      = "ルート証明書"
  "MergeCert.PfxGenerated"                   = "PFX 生成完了"
  "MergeCert.PfxCopiedFromSource"            = "顧客提供 PFX を復号してコピー"
  "MergeCert.PfxCopiedAsIs"                  = "顧客提供 PFX をそのままコピー"
  "MergeCert.PfxFoundInSource"               = "顧客提供の PFX が見つかりました: {0}"
  "MergeCert.PfxRegenPrompt"                 = "新しい PFX を再生成しますか？(y/N)"
  "MergeCert.PfxRegenChosen"                 = "PFX を再生成します。"
  "MergeCert.SyncPrompt"                     = "関連ファイル(.key/.csr/.tsv)もマージ先へ同期しますか？(y/N)"
  "MergeCert.Synced"                         = "同期完了: {0}"
  "MergeCert.SyncSkipped"                    = "同期をスキップしました。"

  # Sync-ToMerged.ps1
  "SyncToMerged.KeyDecrypted"                = "(復号済み)"

  "MergeCert.ChainFromClient"                = "[情報] クライアント証明書内の残りブロックをチェーンとして使用します。"
  "MergeCert.NoChainData"                    = "チェーンファイル用の証明書が見つかりません。"
  "MergeCert.NoCertBlock"                    = "クライアント証明書に CERT ブロックが見つかりません。"
  "MergeCert.AutoFetchStart"                 = "[情報] AIA から発行者証明書を自動取得します..."
  "MergeCert.AutoFetchUrl"                   = "[情報] AIA URL: {0}"
  "MergeCert.AutoFetchSaved"                 = "[成功] ダウンロード完了: {0}"
  "MergeCert.AutoFetchFailed"                = "[警告] AIA URL から取得できませんでした: {0}"
  "MergeCert.AutoFetchNoAia"                 = "[警告] 証明書に AIA (CA Issuers) URL が見つかりません: {0}"
  "MergeCert.AutoFetchNeedOpenSsl"           = "[警告] OpenSSL が見つからないため自動取得を無効化します。"
  "MergeCert.CrossRootHint"                  = "[情報] 交差ルート証明書を使用しています（{0}）。通常ブラウザの信頼チェーンに影響しません。"
  "MergeCert.RootDir"                        = "[DIR] RootDir: {0}"
  "MergeCert.OutDir"                         = "[DIR] OutDir : {0}"
  "MergeCert.NoTargets"                      = "[情報] 対象の証明書(.cer/.crt/.pem)が見つかりません"
  "MergeCert.NoIntermediateCandidates"       = "中間証明書が未指定で、かつルート直下に候補が見つかりません。-IntermediateCert を指定してください。"
  "MergeCert.MultiIntermediateMatched"       = "中間証明書の候補が複数一致しました（issuer/subject）。誤結合防止のため -IntermediateCert を指定してください。`n{0}"
  "MergeCert.NoIntermediateMatched"          = "中間証明書の自動選択に失敗しました（issuer と一致する subject がありません）。誤結合防止のため結合を中止します。`nissuer={0}`n候補:`n{1}"
  "MergeCert.OneCandidateButNoVerify"        = "中間証明書は 1 件ありますが、issuer/subject の一致確認ができないため自動選択しません。-IntermediateCert を明示指定してください: {0}"
  "MergeCert.MultiCandidatesNeedSpecify"     = "中間証明書が未指定で、候補が複数あります。誤結合防止のため -IntermediateCert を指定してください。`n{0}"
  "MergeCert.RootNeedOpenSsl"                = "ルート/交差証明書の自動選択に OpenSSL が必要です。"
  "MergeCert.RootIssuerMissing"              = "中間証明書の issuer を取得できません: {0}"
  "MergeCert.MultiRootMatched"               = "ルート/交差証明書の候補が複数一致しました（issuer/subject）。誤結合防止のため中止します。`n{0}"
  "MergeCert.NoRootMatched"                  = "ルート/交差証明書の自動選択に失敗しました（issuer と一致する subject がありません）。誤結合防止のため中止します。`nissuer={0}`n候補:`n{1}"
  "MergeCert.RootDirNotFound"                = "RootDir が見つかりません: {0}"
  "MergeCert.BatchTarget"                    = "対象: {0}"
  "MergeCert.BatchIntermediate"              = "中間: {0}"
  "MergeCert.BatchIntermediateAuto"          = "（自動選択）"
  "MergeCert.BatchRoot"                      = "交差ルート: {0}"
  "MergeCert.BatchRootCA"                    = "ルートCA: {0}"
  "MergeCert.BatchPlan"                      = "[予定] {0}"
  "MergeCert.BatchPlanMerge2"                = "2 枚結合"
  "MergeCert.BatchPlanMerge3"                = "3 枚結合"
  "MergeCert.BatchPlanSkip"                  = "スキップ"
  "MergeCert.BatchPrompt"                    = "Enter=続行 / s=スキップ / q=終了"
  "MergeCert.BatchMenuTitle"                 = "操作を選択してください"
  "MergeCert.BatchMenuMerge2"                = "2 枚結合"
  "MergeCert.BatchMenuMerge3"                = "3 枚結合"
  "MergeCert.BatchMenuMerge3Rec"             = "3 枚結合(推奨)"
  "MergeCert.BatchMenuMerge4"                = "4 枚結合（ルートCA含む）"
  "MergeCert.BatchMenuSkip"                  = "スキップ"
  "MergeCert.BatchMenuBack"                  = "戻る"
  "MergeCert.BatchMenuQuit"                  = "終了"
  "MergeCert.BatchCertMenuTitle"             = "証明書を選択"
  "MergeCert.RootRequired"                   = "選択した結合モードに対応するルート/交差証明書が見つかりません。"

  # Convert-KeyToPlaintext.ps1
  "DecryptKey.PathNotFound"                  = "Path が見つかりません: {0}"
  "DecryptKey.KeyHeader"                     = "[秘密鍵] {0}"
  "DecryptKey.EncryptedLine"                 = "[情報] 暗号化: {0}"
  "DecryptKey.SkipPlain"                     = "[スキップ] 既に平文の秘密鍵です（復号不要）"
  "DecryptKey.PassFilesLine"                 = "[PASS] パスワードファイル({0}): {1}"
  "DecryptKey.PassEnvLine"                   = "[PASS] 環境変数 PASS_FILE: 設定あり（{0} / {1}）"
  "DecryptKey.PassEnvUnset"                  = "[PASS] 環境変数 PASS_FILE: 未設定"
  "DecryptKey.NoPassphrase"                  = "パスフレーズが見つかりません（対話入力はしません）。{0} または PASS_FILE を用意してください。"
  "DecryptKey.WhatThisDoes"                  = "[情報] このツールは、暗号化された秘密鍵を「パスワード不要の配布用 key」に変換します。"
  "DecryptKey.OutputLine"                    = "[情報] 出力先: {0}"
  "DecryptKey.InPlaceWillReplace"            = "[情報] -InPlace を使うと、元の key と同じファイル名で置き換えます（事前にバックアップを作成）。"
  "DecryptKey.InPlaceConfirmPrompt"          = "元の key を同名で置き換えますか？ [Y/N]"
  "DecryptKey.OutExistsConfirmPrompt"        = "既存の出力をバックアップして上書きしますか？ [Y/N]"
  "DecryptKey.BackupLineOut"                 = "[BAK] 既存の出力ファイルを退避: {0}"
  "DecryptKey.SkipByUser"                    = "[スキップ] ユーザー選択により、この鍵の変換を中止しました"
  "DecryptKey.BackupFailed"                  = "バックアップ作成に失敗しました: {0}"
  "DecryptKey.BackupLine"                    = "[BAK] 元の暗号化 key を退避: {0}"
  "DecryptKey.InPlaceLine"                   = "[情報] -InPlace のため、復号後のファイル名は変更しません: {0}"
  "DecryptKey.OutExistsNoOverwrite"          = "出力先に既にファイルが存在します: {0}"
  "DecryptKey.DecryptFailed"                 = "復号に失敗しました（パスフレーズ不一致の可能性）。"
  "DecryptKey.StillEncrypted"                = "復号結果が暗号化のままです（想定外）。出力を確認してください: {0}"
  "DecryptKey.Done"                          = "[成功] 復号 key: {0}"
  "DecryptKey.NoKeys"                        = "[情報] 対象の .key が見つかりません"
  "DecryptKey.NgPath"                        = "[失敗] {0}"
  "DecryptKey.NgMsg"                         = "[失敗] {0}"

  # New-CertificateSigningRequest.ps1
  "MakeCsr.CnRequired"                       = "CN は必須です。"
  "MakeCsr.SubjectMissing"                   = "Subject が未指定です。-Subject を渡すか、-C/-ST/-L/-O を全て指定してください。"
  "MakeCsr.OutExistsNoOverwrite"             = "出力先に既にファイルが存在します（上書き防止）: {0}`n再生成する場合は -Overwrite を指定してください。"
  "MakeCsr.PassFileUnreadable"               = "PassFile からパスフレーズを読み取れません: {0}"
  "MakeCsr.DoneKey"                          = "[成功] 秘密鍵: {0}"
  "MakeCsr.DoneCsr"                          = "[成功] CSR   : {0}"
  "MakeCsr.PreviewTitle"                     = "[情報] CSR プレビュー（Subject / SAN）"
  "MakeCsr.SanMenuTitle"                     = "SAN 設定"
  "MakeCsr.SanMenuOptionCn"                  = "CN のみ"
  "MakeCsr.SanMenuOptionNone"                = "SAN なし"
  "MakeCsr.SanMenuOptionDns"                 = "DNS 追加"
  "MakeCsr.SanMenuOptionMixed"               = "DNS/IP 追加"
  "MakeCsr.SanMenuPrompt"                    = "選択 (Enter=1)"
  "MakeCsr.SanInputDns"                      = "DNS を入力（カンマ区切り）"
  "MakeCsr.SanInputMixed"                    = "SAN を入力（DNS: / IP: 可、カンマ区切り）"

  # Export-CertificateModulus.ps1
  "ShowModulus.Title"                        = "========== 証明書/秘密鍵 Modulus 一覧 =========="
  "ShowModulus.CreatedAt"                    = "作成日時: {0}"
  "ShowModulus.SectionCert"                  = "証明書 (.cer, .crt, .pem)"
  "ShowModulus.SectionKey"                   = "秘密鍵 (.key)"
  "ShowModulus.GroupMatch"                   = "【ペア一致 (Matched)】"
  "ShowModulus.GroupCertOnly"                = "【証明書のみ (Cert Only)】"
  "ShowModulus.GroupKeyOnly"                 = "【秘密鍵のみ (Key Only)】"
  "ShowModulus.Calculating"                  = "Modulus 算出中..."
  "ShowModulus.ModulusHash"                  = "Modulus (SHA256): {0}"
  "ShowModulus.InvalidCert"                  = "[無効な証明書、もしくはファイル内に複数の証明書が含まれています]"
  "ShowModulus.SkipEncryptedKey"             = "[暗号化された秘密鍵のためスキップ: {0} もしくは -PassFile / 環境変数 PASS_FILE を指定してください]"
  "ShowModulus.KeyReadError"                 = "[秘密鍵の読み取りエラー、もしくは形式が不正です]"
  "ShowModulus.SummaryTitle"                 = "概要"
  "ShowModulus.SummaryCertCount"             = "処理した証明書数: {0}"
  "ShowModulus.SummaryKeyCount"              = "処理した秘密鍵数: {0}"
  "ShowModulus.Advice1"                      = "一致確認は Modulus 値を比較してください。"
  "ShowModulus.Advice2"                      = "証明書と秘密鍵は Modulus が同一ならペアです。"
  "ShowModulus.ConsoleTitle"                 = "[成功] 概要"
  "ShowModulus.SavedTo"                      = "保存先: {0}"

  # Test-CertificateKeyMatch.ps1
  "VerifyMatch.ReportTitle"                  = "証明書/秘密鍵/CSR 一致確認レポート"
  "VerifyMatch.CreatedAt"                    = "作成日時: {0}"
  "VerifyMatch.Separator"                    = "=============================================="
  "VerifyMatch.ConsoleTitle"                 = "========== 証明書/秘密鍵/CSR 一致確認 =========="
  "VerifyMatch.Scanning"                     = "フォルダ走査中（モード={0}）..."
  "VerifyMatch.FolderMissing"                = "[情報] フォルダがありません: {0}"
  "VerifyMatch.Checking"                     = "[{0}] 確認中: {1}\\{2}\\{3}"
  "VerifyMatch.ReportHeader"                 = "[{0}] ルート: {1}  機関: {2}  サーバ: {3}"
  "VerifyMatch.DetectedFiles"                = "検出ファイル:"
  "VerifyMatch.DetectedCert"                 = "  [証明書] {0}"
  "VerifyMatch.DetectedKey"                  = "  [秘密鍵] {0}"
  "VerifyMatch.DetectedCsr"                  = "  [CSR ] {0}"
  "VerifyMatch.ConsoleCertMissing"           = "  証明書: なし"
  "VerifyMatch.ConsoleCertFound"             = "  証明書: あり"
  "VerifyMatch.ConsoleKeyMissing"            = "  秘密鍵: なし"
  "VerifyMatch.ConsoleKeyFound"              = "  秘密鍵: あり"
  "VerifyMatch.ConsoleCsrMissing"            = "  CSR  : なし"
  "VerifyMatch.ConsoleCsrFound"              = "  CSR  : あり"
  "VerifyMatch.Judgement"                    = "--- 判定 ---"
  "VerifyMatch.NoFiles"                      = "[エラー] 対象ファイルがありません"
  "VerifyMatch.MatchCertKey"                 = "[成功] 証明書 と 秘密鍵 の Modulus 一致"
  "VerifyMatch.MismatchCertKey"              = "[エラー] 証明書 と 秘密鍵 の Modulus 不一致"
  "VerifyMatch.MatchCertKeyDetail"           = "[成功] 証明書({0}) と 秘密鍵({1}) の Modulus 一致"
  "VerifyMatch.MismatchCertKeyDetail"        = "[エラー] 証明書({0}) と 秘密鍵({1}) の Modulus 不一致"
  "VerifyMatch.MatchCertCsr"                 = "[成功] 証明書 と CSR の Modulus 一致"
  "VerifyMatch.MismatchCertCsr"              = "[エラー] 証明書 と CSR の Modulus 不一致"
  "VerifyMatch.MatchCertCsrDetail"           = "[成功] 証明書({0}) と CSR({1}) の Modulus 一致"
  "VerifyMatch.MismatchCertCsrDetail"        = "[エラー] 証明書({0}) と CSR({1}) の Modulus 不一致"
  "VerifyMatch.MatchKeyCsr"                  = "[成功] 秘密鍵 と CSR の Modulus 一致"
  "VerifyMatch.MismatchKeyCsr"               = "[エラー] 秘密鍵 と CSR の Modulus 不一致"
  "VerifyMatch.MatchKeyCsrDetail"            = "[成功] 秘密鍵({0}) と CSR({1}) の Modulus 一致"
  "VerifyMatch.MismatchKeyCsrDetail"         = "[エラー] 秘密鍵({0}) と CSR({1}) の Modulus 不一致"
  "VerifyMatch.ConsoleMatchCertKey"          = "  証明書 <-> 秘密鍵: 一致"
  "VerifyMatch.ConsoleMismatchCertKey"       = "  証明書 <-> 秘密鍵: 不一致"
  "VerifyMatch.ConsoleMatchCertCsr"          = "  証明書 <-> CSR: 一致"
  "VerifyMatch.ConsoleMismatchCertCsr"       = "  証明書 <-> CSR: 不一致"
  "VerifyMatch.ConsoleMatchKeyCsr"           = "  秘密鍵 <-> CSR: 一致"
  "VerifyMatch.ConsoleMismatchKeyCsr"        = "  秘密鍵 <-> CSR: 不一致"
  "VerifyMatch.ConsoleInsufficient"          = "  [警告] 比較に必要なファイルが不足しています"
  "VerifyMatch.Insufficient"                 = "[警告] 比較に必要なファイルが不足しています"
  "VerifyMatch.ConsoleFinalOk"               = "  最終結果: 一致（有効なセット）"
  "VerifyMatch.ConsoleFinalNg"               = "  最終結果: 不一致（無効なセット）"
  "VerifyMatch.FinalOk"                      = "[結果] 一致（有効なセット）"
  "VerifyMatch.FinalNg"                      = "[結果] 不一致（無効なセット）"
  "VerifyMatch.SummaryTitle"                 = "概要"
  "VerifyMatch.SummaryTotal"                 = "確認件数: {0}"
  "VerifyMatch.SummaryOk"                    = "一致（有効）: {0}"
  "VerifyMatch.SummaryNg"                    = "不一致（無効）: {0}"
  "VerifyMatch.SavedTo"                      = "保存先: {0}"
  "VerifyMatch.ReportSavedTo"                = "レポート保存先: {0}"

  # New-CertificateSigningRequestFromOld.ps1
  "Renew.MenuTitle"                          = "複数の機関が見つかりました。処理する機関を選択してください。"
  "Renew.MenuHint"                           = "（例: 1  または  1,3  /  all  /  q）"
  "Renew.MenuPrompt"                         = "選択"
  "Renew.NoInteractive"                      = "対話入力が利用できない環境です。-Org で機関を指定するか、-All を指定してください。"
  "Renew.Cancelled"                          = "キャンセルしました。"
  "Renew.InvalidInput"                       = "[警告] 入力が不正です。もう一度入力してください。"
  "Renew.CnMissingInSubject"                 = "Subject から CN を取得できません"
  "Renew.New.NotGenerated"                   = "new=未生成"
  "Renew.New.NotGeneratedRoot"               = "new=未生成 (0/{0})"
  "Renew.New.GeneratedRoot"                  = "new=生成済 ({0}/{1})"
  "Renew.New.GeneratedNoLatest"              = "new=生成済 (sets~{0}, csr={1}, key={2})"
  "Renew.New.GeneratedWithLatest"            = "new=生成済 (sets~{0}, csr={1}, key={2}, updated={3})"
  "Renew.OldDirMissing"                      = "OldDir が存在しません: {0}"
  "Renew.RootNoCerts"                        = "old 直下に証明書がありません。-Org (root) は選択できません。"
  "Renew.OrgFolderMissing"                   = "指定された機関フォルダが存在しません: {0}"
  "Renew.NoOrgFound"                         = "old 配下に機関フォルダ/証明書が見つかりません: {0}"
  "Renew.MultiOrgNeedSpecify"                = "複数の機関が見つかりました。-Org で指定するか、-All を指定してください。"
  "Renew.MultiOverwriteForbidden"            = "危険な操作です：複数機関に対して -Overwrite は使用できません。-Org で 1 機関に絞って実行してください。"
  "Renew.MultiOverwriteWarn"                 = "[警告] 複数機関を選択した状態で -Overwrite が指定されています。既存の .key/.csr をバックアップして再生成します。"
  "Renew.MultiOverwriteConfirmPrompt"        = "続行する場合は YES と入力してください"
  "Renew.CnNotFound"                         = "CN を取得できません: cert={0} subject=[{1}] csr=[{2}]"
  "Renew.BackupKeyFail"                      = "既存の .key をバックアップできません: {0}"
  "Renew.BackupCsrFail"                      = "既存の .csr をバックアップできません: {0}"
  "Renew.OutExistsNoOverwrite"               = "出力先に既にファイルが存在します（上書き防止）: {0}`n再生成する場合は -Overwrite を指定してください。"
  "Renew.DoneTitle"                          = "生成完了:"
  "Renew.ShowInfo.OpenSsl"                   = "OpenSSL: {0}"
  "Renew.ShowInfo.OldDir"                    = "OldDir : {0}"
  "Renew.ShowInfo.NewDir"                    = "NewDir : {0}"
  "Renew.ShowInfo.Version"                   = "OpenSSL version: {0}"
  "Renew.Table.Org"                          = "機関"
  "Renew.Table.Cn"                           = "CN"
  "Renew.Table.RsaBits"                      = "鍵長"
  "Renew.Table.San"                          = "SAN"
  "Renew.Table.OutDir"                       = "出力先"
  "Renew.SanMenuTitle"                       = "SAN 設定"
  "Renew.SanMenuCurrent"                     = "現在: {0}"
  "Renew.SanMenuOptionKeep"                  = "現在の SAN を使用"
  "Renew.SanMenuOptionCn"                    = "CN のみ"
  "Renew.SanMenuOptionAppend"                = "追加"
  "Renew.SanMenuOptionReplace"               = "置換"
  "Renew.SanMenuPrompt"                      = "選択 (Enter=1)"
  "Renew.SanInputAppend"                     = "追加する SAN（DNS:/IP: 可、カンマ区切り）"
  "Renew.SanInputReplace"                    = "置換 SAN（DNS:/IP: 可、カンマ区切り）"

  "Renew.OutExistsPrompt"                    = "出力先に既にファイルが存在します。続行しますか？`n{0}"
  "Renew.ConflictOverwrite"                  = "はい (上書き再生成 / 既存は自動バックアップ)"
  "Renew.ConflictSkip"                       = "この証明書をスキップして次へ"
  "Renew.ConflictBack"                       = "前のメニューに戻る"
  "Renew.ConflictCancel"                     = "いいえ (処理を中止して戻る)"
  "Renew.PressAnyKeyToReturn"                = "生成が完了しました。何かキーを押してメニューに戻ります..."

  # TSV Generation
  "Renew.TsvConfirmTitle"                    = "TSV データ確認 ({0})"
  "Renew.TsvLabelDept"                       = "部門"
  "Renew.TsvLabelOrgName"                    = "機関名"
  "Renew.TsvLabelContact"                    = "担当者"
  "Renew.TsvLabelSoftware"                   = "ソフトウェア"
  "Renew.TsvExistsWarn"                      = "[警告] TSV ファイルが既に存在します: {0}"
  "Renew.TsvOverwritePrompt"                 = "上書きしますか？ (y/N)"
  "Renew.TsvBackedUp"                        = "[情報] 既存 TSV をバックアップしました: {0}"
  "Renew.TsvAppended"                        = "[成功] TSV に追記しました"
  "Renew.TsvSkipped"                         = "[スキップ] TSV 出力をスキップしました"
  "Renew.TsvGenerateTitle"                   = "TSV を生成しますか？ ({0})"
  "Renew.TsvGenerateYes"                     = "はい（TSV を生成）"
  "Renew.TsvGenerateNo"                      = "いいえ（TSV を生成しない）"
  "Renew.TsvGeneratePrompt"                  = "TSV を生成しますか？ ({0}) (y/N)"

  # File Matching Validation
  "Matching.Title"                           = "一致性検証"
  "Matching.KeyCsr"                          = "KEY ⇔ CSR (モジュラス)"
  "Matching.KeyCer"                          = "KEY ⇔ CER (モジュラス)"
  "Matching.CsrTsvCn"                        = "CSR ⇔ TSV (CN)"
  "Matching.CsrTsvContent"                   = "CSR ⇔ TSV (内容)"

  # Common error messages
  "Common.FolderNotFound"                    = "[情報] {0} フォルダがありません: {1}"
  "Common.NoTargetFiles"                     = "[情報] 対象ファイルが見つかりません"
  "Common.NoCertFiles"                       = "[情報] 証明書ファイル(.cer/.crt/.pem) がありません（中間証明書同梱チェックは実行されません）"
  "Common.ErrorNg"                           = "[NG] {0}"

  # Get-CertificateInfo menu
  "CheckBasic.Menu.RootTitle"                = "表示対象を選択"
  "CheckBasic.Menu.OrgTitle"                 = "機関を選択（{0}）"
  "CheckBasic.Menu.CertTitle"                = "証明書を選択（{0}）"
  "CheckBasic.Menu.FileTitle"                = "ファイルを選択（{0}）"
  "CheckBasic.Menu.Instruction"              = "↑↓ で選択 / Enter 決定 / ESC 戻る"
  "CheckBasic.Menu.NoCerts"                  = "証明書が見つかりません"
  "CheckBasic.Menu.BackPrompt"               = "いずれかのキーを押して戻る"

  # Test-CertificateKeyMatch.ps1 detail sections
  "VerifyMatch.Detail.CertInfo"              = "--- 証明書情報 ---"
  "VerifyMatch.Detail.KeyInfo"               = "--- 秘密鍵情報 ---"
  "VerifyMatch.Detail.CsrInfo"               = "--- CSR 情報 ---"
  "VerifyMatch.Detail.Subject"               = "Subject:"
  "VerifyMatch.Detail.Modulus"               = "Modulus:"

  # Request-LetsEncryptCertificate.ps1
  # Request-LetsEncryptCertificate.ps1
  "LE.InputDomainPrompt"                     = "証明書を発行するドメインを入力してください。"
  "LE.InputEmailPrompt"                      = "Let's Encrypt 登録用メールアドレスを入力してください。"
  "LE.CommandNotFound"                       = "コマンドが見つかりません: {0}"
  "LE.Ready"                                 = "== 準備完了 =="
  "LE.Domain"                                = "ドメイン: {0}"
  "LE.CleaningWorkDir"                       = "[情報] 既存の作業ディレクトリを削除中: {0}"
  "LE.ReusingWorkDir"                        = "[情報] 既存の作業ディレクトリを再利用: {0}"
  "LE.ChallengeDir"                          = "ローカル challenge ファイル配置先:"
  "LE.ServerChallengeDir"                    = "サーバー側 challenge 配置先（ヒント）:"
  "LE.ExportDir"                             = "証明書エクスポート先:"
  "LE.DockerMountCheck"                      = "== Docker マウント自己チェック =="
  "LE.DockerMountFailed"                     = "Docker マウント自己チェック失敗: コンテナ内で /work/auth.sh が見えません。Docker Desktop のファイル共有設定を確認してください。"
  "LE.StartingCertbot"                       = "== certbot 起動（Docker） =="
  "LE.CertbotAttempt"                        = "[情報] certbot 実行 {0}/{1}"
  "LE.CertbotFailed"                         = "certbot が失敗しました（終了コード: {0}）。ログを確認してください: {1}"
  "LE.CaaServfailRetryDetected"              = "[警告] CAA の DNS SERVFAIL を検出しました（{0}/{1} 回目）。{2} 秒後に再試行します。"
  "LE.CaaServfailRetryExhausted"             = "[警告] CAA の DNS SERVFAIL が継続したため、最大試行回数 {0} 回に達しました。"
  "LE.RateLimitError"                        = "[警告] Let's Encrypt のレート制限に達しました"
  "LE.RateLimitRetryAfter"                   = "再試行可能時刻: {0}"
  "LE.RateLimitHint"                         = "ヒント: Let's Encrypt は同一ドメインセットに対して 168 時間（7日）あたり 5 件の証明書発行制限があります。`n詳細: https://letsencrypt.org/docs/rate-limits/"
  "LE.RateLimitFailed"                       = "レート制限により証明書の取得に失敗しました。上記の再試行可能時刻まで待つか、別のドメインで試してください。"
  "LE.ErrorLogTail"                          = "エラーログ（末尾50行）:"
  "LE.Exporting"                             = "== 証明書をホストへエクスポート =="
  "LE.ExportFailedTrying"                    = "[警告] {0} へのエクスポートに失敗しました。フォールバック先 {1} を試行中..."
  "LE.ExportFailed"                          = "エクスポート失敗: {0} と {1} の両方に書き込めません。Docker Desktop のファイル共有設定/セキュリティソフトを確認してください。"
  "LE.ExportDirCreateFailed"                 = "[警告] エクスポート先ディレクトリの作成に失敗しました: {0}。フォールバック先: {1}"
  "LE.ExportDirFallback"                     = "[情報] エクスポート先を変更しました: {0}"
  "LE.ExportZeroBytes"                       = "エクスポートされたファイルが 0 バイトです（{0}={1}, {2}={3}）。権限/ブロックを確認してください。"
  "LE.ExportFilesMissing"                    = "エクスポートされたファイルが見つかりません: {0} または {1}"
  "LE.ExportSuccess"                         = "[成功] {0} ({1} bytes)"
  "LE.CompletedMsg"                          = "Let's Encrypt 証明書の取得が完了しました。"
  "LE.PressAnyKeyToReturn"                   = "何かキーを押してメニューに戻ります..."

  # Request-SelfSignedCertificate.ps1
  "SS.Menu.Title"                            = "自己署名証明書（{0} 日 / 約 {1} 年）"
  "SS.Menu.ValidityTitle"                    = "証明書の有効期間を選択してください"
  "SS.Validity.90d"                          = "90 日"
  "SS.Validity.1y"                           = "1 年（365 日）"
  "SS.Validity.3y"                           = "3 年（1095 日）"
  "SS.Validity.10y"                          = "10 年（3650 日）"
  "SS.Menu.Quick"                            = "簡易作成（old の機関証明書CNから生成）"
  "SS.Menu.Custom"                           = "個別設定作成（Subject / 出力先を指定）"
  "SS.Menu.QuickSelectOrg"                   = "機関を選択（簡易作成）"
  "SS.Menu.NoOrg"                            = "old 配下に機関フォルダが見つかりません。"
  "SS.Menu.NoCertInOrg"                      = "選択した機関に証明書ファイルが見つかりません: {0}"
  "SS.Prompt.CN"                             = "CN"
  "SS.Prompt.SubjectOptional"                = "Subject（任意）"
  "SS.Prompt.SANOptional"                    = "SAN（任意）"
  "SS.Prompt.OutDirOptional"                 = "出力先（任意）"
  "SS.InputCnPrompt"                         = "CN を入力してください（例: example.com）。"
  "SS.InputSubjectPrompt"                    = "必要な場合は Subject を入力してください（未入力なら /CN=<CN>）。"
  "SS.InputSanPrompt"                        = "SAN を入力してください（任意）。未入力時は DNS:CN を自動設定します。"
  "SS.InputOutDirPrompt"                     = "必要な場合は出力先を指定してください（未入力時は既定値）。"
  "SS.OpenSslNotFound"                       = "OpenSSL が見つかりません。指定パスを確認するか openssl コマンドを利用可能にしてください: {0}"
  "SS.OutExistsNoOverwrite"                  = "出力先に既存ファイルがあります。上書きする場合は -Overwrite を指定してください。`n{0}"
  "SS.Starting"                              = "== 自己署名証明書を生成中（{0} 日 / 約 {1} 年） =="
  "SS.Info.CN"                               = "CN: {0}"
  "SS.Info.Subject"                          = "Subject: {0}"
  "SS.Info.SAN"                              = "SAN: {0}"
  "SS.Info.Validity"                         = "有効期間: {0} 日（約 {1} 年）"
  "SS.Info.OutDir"                           = "出力先: {0}"
  "SS.Done.Key"                              = "[成功] 秘密鍵: {0}"
  "SS.Done.Cert"                             = "[成功] 証明書: {0}"
  "SS.Done.NotAfter"                         = "[成功] 有効期限: {0}"
  "SS.Done.Warning"                          = "[注意] 自己署名証明書は公的 CA 証明書ではありません。内部用途で利用してください。"
  "SS.Quick.StartOrg"                        = "== 機関処理開始: {0} =="
  "SS.Quick.ProcessingCert"                  = "[処理] {0} -> CN={1}"
  "SS.Quick.CnFromCertFailed"                = "[警告] CN を抽出できませんでした: {0}"
  "SS.Quick.SkipDuplicateCn"                 = "[スキップ] 重複 CN を検出: {0}"
  "SS.Quick.Completed"                       = "== 機関処理完了: {0} =="
  "SS.Quick.SuccessCount"                    = "成功件数: {0}"
  "SS.Quick.FailCount"                       = "失敗件数: {0}"
  "SS.PressAnyKeyReturnOrg"                  = "何かキーを押して機関一覧に戻ります..."

  # Repair-PemFile.ps1
  "RepairPem.ReadFailed"                     = "ファイルの読み取りに失敗しました: {0}"
  "RepairPem.ZeroBytes"                      = "ファイルが 0 バイトです: {0}"
  "RepairPem.EmptyAfterBom"                  = "BOM 除去後にファイルが空になりました: {0}"
  "RepairPem.NoPemBlock"                     = "[{0}] 有効な PEM ブロック（BEGIN/END）が見つかりません。ファイルが PEM 形式でないか破損しています: {1}"
  "RepairPem.ParseFailed"                    = "[{0}] PEM ブロックの解析に失敗しました: {1}"
  "RepairPem.TooShort"                       = "[{0}] PEM 本文が短すぎます（{1} 文字）。切り詰め/破損の可能性があります: {2}"
  "RepairPem.InvalidHeader"                  = "[{0}] 最初の行が不正です: {1}"
  "RepairPem.BackupSection"                  = "== バックアップ作成 =="
  "RepairPem.BackupCreated"                  = "{0} バックアップ: {1}"
  "RepairPem.NormalizeSection"               = "== PEM 正規化 =="
  "RepairPem.VerifySection"                  = "== 検証 =="
  "RepairPem.FileInfo"                       = "{0}: {1} bytes, blocks={2}, first='{3}', last='{4}'"
  "RepairPem.NginxParamsRequired"            = "-TestNginx を使用する場合は -NginxExe と -NginxConf を指定してください。"
  "RepairPem.NginxTestSection"               = "== nginx -t =="
  "RepairPem.NginxTestFailed"                = "nginx -t が失敗しました（終了コード: {0}）"
  "RepairPem.Menu.SelectSource"              = "PEM 修復元を選択してください"
  "RepairPem.Menu.SelectPair"                = "{0} から修復する PEM ペアを選択してください"
  "RepairPem.Menu.Manual"                    = "手動入力`n  fullchain.pem と privkey.pem のパスを直接入力"
  "RepairPem.Menu.FullchainPrompt"           = "fullchain PEM のパス"
  "RepairPem.Menu.PrivkeyPrompt"             = "privkey PEM のパス"
  "RepairPem.Menu.NoCandidates"              = "PEM ペア候補が見つかりませんでした: {0}"
  "RepairPem.Success"                        = "[成功] PEM ファイルの修復が完了しました。"
  "RepairPem.Failed"                         = "[失敗] {0}"
  "RepairPem.RestoreHint"                    = "ヒント: 作成した .bak_ タイムスタンプファイルで復元できます。"

  # Install-Dependencies.ps1
  "Deps.Title"                               = "SSL Toolkit 依存ツールセットアップ"
  "Deps.AlreadyInstalled"                    = "[インストール済] OpenSSL が既に存在します: {0}"
  "Deps.Version"                             = "バージョン: {0}"
  "Deps.UseForceHint"                        = "再ダウンロードするには -Force パラメータを使用してください。"
  "Deps.Downloading"                         = "[ダウンロード] ポータブル版 OpenSSL をダウンロード中..."
  "Deps.TryingSource"                        = "[試行] ダウンロード元: {0}"
  "Deps.DownloadTooSmall"                    = "[警告] ダウンロードファイルが小さすぎます。"
  "Deps.Extracting"                          = "[展開] 展開中..."
  "Deps.OpenSslNotFoundInArchive"            = "[警告] アーカイブ内に openssl.exe が見つかりません。"
  "Deps.ExtractedButNotWorking"              = "[警告] 展開しましたが OpenSSL が動作しません。"
  "Deps.DownloadFailed"                      = "[失敗] ダウンロード失敗: {0}"
  "Deps.InstallSuccess"                      = "[成功] OpenSSL のインストールが完了しました！"
  "Deps.InstalledTo"                         = "インストール先: {0}"
  "Deps.AutoFailed"                          = "[失敗] 自動ダウンロードに失敗しました。手動でインストールしてください:"
  "Deps.ManualGuide"                         = "手動インストール手順:"
  "Deps.ManualStep1"                         = "  1. https://slproweb.com/products/Win32OpenSSL.html から Win64 OpenSSL をダウンロード"
  "Deps.ManualStep2"                         = "  2. openssl.exe と関連 DLL を以下にコピー: {0}"
  "Deps.ManualStep3"                         = "  3. または Git for Windows をインストール（OpenSSL 同梱）"
  "Deps.ManualAlt1"                          = "代替手段: winget install ShiningLight.OpenSSL"
  "Deps.ManualAlt2"                          = "代替手段: Git for Windows をインストール (https://git-scm.com/)"
}
